### ISSUE TITLE
Suggestion: Sneaky Mob Filters

### ISSUE THREAD

**Issue by psychofad** [Darkhax-Minecraft/Dark-Utilities#10]
As the Suggestion implies, I would like to be able to make the mob filters (specifically the player filter) look like other blocks similar to how the sneaky false block works.

**Comment by darkhax** [comment]
This is a planned feature. I plan to give a lot of blocks from this mod access to the sneaky system.

**Comment by psychofad** [comment]
any progress on this?

**Comment by darkhax** [comment]
After reflecting on it further, I am not sure if I want to implement this feature. It's on the list, but something I will have to consider. It will remain in limbo for now, but definitely something I want to eventually work on adding.

**Comment by mrtomwolf** [comment]
I want this =(

**Comment by carsongmiller** [comment]
Anyone know if this ever got implemented?
