### ISSUE TITLE
Server crash after apparent fix

### ISSUE THREAD

**Issue by Firestar311** [Darkhax-Minecraft/Dark-Utilities#101]
So I downloaded the 161 version of dark utilites did not fix the ChatFormatting crash from a previous issue. I am still getting it
https://pastebin.com/h7Rr7ePV

**Comment by darkhax** [comment]
Huh, this is very weird. I specifically tested the code on my own server to make sure it was fixed, and didn't run into the issue. However the crash log does make sense. I am wondering if Mojang secretly pushed a new version of their realms library and we don't have the same one. Either way I will attempt to fix this issue again. Sorry for the trouble.

**Comment by darkhax** [comment]
Okay, this issue *should* be fixed now. Please let me know if it's still not working.

**Comment by Firestar311** [comment]
This issue has been fixed
