### ISSUE TITLE
Recipes aren't showing in JEI [1.12]

### ISSUE THREAD

**Issue by LukeLonas** [Darkhax-Minecraft/Dark-Utilities#103]
All recipes won't show in JEI, but I'm still able to see the information tab for all the items.

(What I see when I try to get a recipe)
http://i.imgur.com/2zHClap.png

(What I see when I try to get the usages of an item)
http://i.imgur.com/9B6by4b.png

- Bookshelf: 2.0.0.414
- Dark Utils: 1.6.162
- JEI: 4.7.1.74
- Forge: 2406

**Comment by darkhax** [comment]
Are you still having this issue with the latest version of all mods involved? I've been unable to reproduce the error.

**Comment by LukeLonas** [comment]
Yeah, I'm still having the issues with the most up-to-date version of all the mods and forge.  Hmmm I haven't touched the config and all the other recipes seem to work, so this is strange.

**Comment by darkhax** [comment]
I tested this out in a 1.12 pack using only the mods in question. I can not reproduce this issue, possibly an error in another mod you have downloaded? 

Minecraft 1.12
Bookshelf 2.0.0.415
Dark Utils: 1.6.167
JEI: 4.7.2.77

[Curse Instance DarkUtilsRecipeTest-1.0.zip](https://github.com/Darkhax-Minecraft/Dark-Utilities/files/1160718/DarkUtilsRecipeTest-1.0.zip)


![image](https://user-images.githubusercontent.com/2250798/28393427-e95ac868-6ca3-11e7-9258-702de3890338.png)

**Comment by LukeLonas** [comment]
Well, this is indeed strange.  Thanks for taking the time and trying to figure it out.  I guess I'll just try fiddling around and maybe delete and try regening the config.  I'll close the issue.  Thanks again!

**Comment by LukeLonas** [comment]
Interesting, so I just rebooted the game after deleting the configs and letting them generate again, and that fixed it.  I never messed with the config at all, but that was the fix. 😄
