### ISSUE TITLE
Sneaky False Block spawns Mobs inside (SF 3.0.10)

### ISSUE THREAD

**Issue by Allukart** [Darkhax-Minecraft/Dark-Utilities#104]
Hi,
after starting to play SkyFactory 3 a few weeks ago i wanted to hide some places with the Sneaky False Block and hide it with cobblestone. After doing that and leaving, when i came back a creeper & skeleton spawned inside the blocks (2x2) and on another space where i used it (1x2) too.

So i guess it's not intended and hopefully getting fixed.

Best regards
Allukart

Edith says: I forgot to Mention im using the Curse FTB SkyFactory 3.0.10 Modpack & a nitrado server.

**Comment by darkhax** [comment]
Thanks for reporting the issue. 1.10.2 is an older version of the game, so I won't be pushing a fix for it in the near future. If enough 1.10.2 issues pop up, or a critical issue is uncovered I will include this fix in that round of updates for the older version.
