### ISSUE TITLE
darkutils.cfg Being Created Outside The Minecraft Instance Folder

### ISSUE THREAD

**Issue by dh47** [Darkhax-Minecraft/Dark-Utilities#105]
```
Minecraft 1.11.2
DarkUtilities-1.11.2-1.2.0.147
```

For some reason, the config is being generated outside of the Minecraft instance.

![image](https://user-images.githubusercontent.com/909007/28214584-e83c959a-68fe-11e7-86ec-703b1b19ea26.png)

**Comment by Xathz** [comment]
[Having this issue as well.](https://github.com/Darkhax-Minecraft/Dark-Utilities/blob/93422758fe79dd730489d48a66ed83f19ae60601/src/main/java/net/darkhax/darkutils/DarkUtils.java#L80) 

FMLPreInitializationEvent -> getSuggestedConfigurationFile()

Minecraft 1.11.2
Forge 13.20.1.2414
DarkUtilities 1.2.0.147

**Comment by darkhax** [comment]
Thanks for reporting, this was unintentional. I will be pushing out a final RC for 1.11.2 soon. I want to look into a few other potential 1.11.2 issues first and fix them all at the same time.
