### ISSUE TITLE
Crash when sneak right clicking Tether

### ISSUE THREAD

**Issue by kalsmeer** [Darkhax-Minecraft/Dark-Utilities#107]
Hello,

When I sneak right clicked a tether in DarkUtils-1.12-1.6.162 it crashed my game, and anyone in the area looking at it.
From that point on looking in the general direction of the tether will crash you, making it impossible to remove it.

https://pastebin.com/LUJN7jA4

**Comment by darkhax** [comment]
I was unable to reproduce this specific error, however I can see how it might happen in the code. I've added some safety catches which should help fix this issue, and prevent it from happening in the future. I would appreciate it if you could [download the new version](https://minecraft.curseforge.com/projects/dark-utilities/files/2452753) and see if it's fixed. It will probably take Curse a while to approve it.

**Comment by chooven** [comment]
I had the same issue with  DarkUtils-1.12-1.6.163 (crash on sneak click) and did not have the problem after upgrading to  DarkUtils-1.12-1.6.164, no crash on sneak click.

**Comment by darkhax** [comment]
Thanks for testing @chooven
