### ISSUE TITLE
fatally missing blocks and items

### ISSUE THREAD

**Issue by DnTheMn** [Darkhax-Minecraft/Dark-Utilities#11]
ive noticed that several people have been having issues with setting up servers on allthemods v1.11 and that not your problem but the issue they have is when dark utils is on the mod list it wont let any clients into the server remove the mod its fine any suggestions?

**Comment by darkhax** [comment]
The error would suggest that players are not connecting with the right version installed, or some mod is messing with the item/block list. Dark Utilities also allows players to turn items/blocks off completely, so the server and client must have the same config.

**Comment by DnTheMn** [comment]
they were still having the issue updating the server config with config from singleplayer instance to the server im not pointing the blame onto you or your mod im simply saying that removing your mod fixes it

**Comment by darkhax** [comment]
Typically you don't report an issue unless you know it is an issue. The issue you describe sounds like configs are out of sync. If you need further help, I will need logs.

**Comment by DnTheMn** [comment]
alrighty no worries
