### ISSUE TITLE
Ender Tether broke my (test) worlds when using an ender pearl

### ISSUE THREAD

**Issue by Dakotaraptor** [Darkhax-Minecraft/Dark-Utilities#110]
[https://paste.ee/p/Yw1Iq](https://paste.ee/p/Yw1Iq)

If this is the same crash posted in the other issues I apologize, but it seemed different enough to mention here. This is on 1.11 with Dark Utilities version 1.2.0.147

**Comment by darkhax** [comment]
I am no longer supporting 1.11.2, however if enough small issues pop up, or a critical issue is found, I will fix the issue. Leaving this open for now.
