### ISSUE TITLE
Enchanted rings issue

### ISSUE THREAD

**Issue by shikyo13** [Darkhax-Minecraft/Dark-Utilities#111]
Love the mod, but I can't tell if the enchanted rings are working correctly? I'm using DarkUtils 1.12-1.6.167 and Baubles 1.12-1.5.1 and can't put rings in a baubles slot. When holding in the offhand, I do not notice any haste effects with the engineers ring, and mobs do not catch fire when holding the pyromancers ring and using my sword.

**Comment by darkhax** [comment]
I haven't had a chance to re-add baubles support yet. The mod only updated recently. As for the actual rings themselves, unfortunately they don't work in 1.12. They rely on coremod features, and [things have changed](http://www.minecraftforge.net/forum/topic/58706-regarding-minecraft-112-and-policy-changes/) for coremods in 1.12.

**Comment by shikyo13** [comment]
Ok thanks for the info. Just as an fyi though, I've loaded up my FTB Beyond instance that is running DarkUtils -1.1.8.finalrc2 and while I can put the rings in a bauble slot, I still do not get any effects from them.

**Comment by darkhax** [comment]
Baubles support was added for the charms. The rings have been removed and likely won't be re-added. I have been waiting for a PR to Forge but it has been given the run around for a while and I am not hopeful that it will be added. The rings will potentially be re-added in another form eventually.
