### ISSUE TITLE
Tether Doesn't Seem to be Stopping Teleports

### ISSUE THREAD

**Issue by selonianth** [Darkhax-Minecraft/Dark-Utilities#112]
MC Version: 1.10.2
Mod Version: 1.1.8
Mod Pack: SkyFactory 3

Been having an issue with the tether in particular where it would endermen would teleport out of the kill room, seemingly ignoring the tether.

**Comment by darkhax** [comment]
This issue was reported as fixed in 1.1.8-finalrc2. Either way 1.10.2 is no longer supported.
