### ISSUE TITLE
Shift Right click to turn vector plates

### ISSUE THREAD

**Issue by gigabit101** [Darkhax-Minecraft/Dark-Utilities#113]
I think this might be a cool little addition to the mod

**Comment by darkhax** [comment]
![arrows](https://user-images.githubusercontent.com/2250798/33523832-824e3af2-d7cd-11e7-904f-a8a0f4f969f1.gif)
Stuff is happening

**Comment by gigabit101** [comment]
only took 4 months... ;)

**Comment by darkhax** [comment]
I've been absurdly busy the last few months x)

**Comment by darkhax** [comment]
This is added in the [latest alpha](https://minecraft.curseforge.com/projects/dark-utilities/files/2506687). If the file is not available for download, wait for Curse to approve it.
