### ISSUE TITLE
Ender Tether not catching teleports

### ISSUE THREAD

**Issue by altech6983** [Darkhax-Minecraft/Dark-Utilities#115]
I am on Minecraft 1.10.2, skyfactory 3.0.13, 1.1.8.finalrc2 dark utilities and now the tether doesn't catch the enderman teleports. I have a separate room from my mob grinder that the tether is in so that I can collect soul vials of enderman easy.

I tried destroying the one I already had created and making another but it still doesn't work.

Thank you for the awesome mod. Not sure if this is addressed by the other tether issues.

Sorry to bother you with an unsupported version.

**Comment by altech6983** [comment]
I wanted to add that I reverted to 1.1.7.120 and the ender tether works.

**Comment by darkhax** [comment]
Yes, this bug was introduced by someone else trying to fix another error with the tethers.
