### ISSUE TITLE
[1.12.1] Dark-Utilities doesnt like  Bookshelf 2.1.427

### ISSUE THREAD

**Issue by UnPure** [Darkhax-Minecraft/Dark-Utilities#116]
Was working fine up to 2.0.0.425 of Bookshelf, now it tells me that the mod is missing.

**Comment by darkhax** [comment]
https://github.com/Darkhax-Minecraft/Bookshelf/issues/88

**Comment by Realever** [comment]
the new version has the same error

**Comment by darkhax** [comment]
An update was also needed for bookshelf. https://minecraft.curseforge.com/projects/bookshelf/files/2469466
