### ISSUE TITLE
Doesn't work on 1.12.2

### ISSUE THREAD

**Issue by EmosewaGamer** [Darkhax-Minecraft/Dark-Utilities#118]
Dark Utilities, together with Bookshelf, are 2 of the mods in my pack that don't work on MC 1.12.2
![image](https://user-images.githubusercontent.com/25333164/30588036-7c7268ce-9d35-11e7-954e-323c0f4c8fcf.png)

**Comment by darkhax** [comment]
This should be resolved. If it's not let me know.
