### ISSUE TITLE
[Feature request] Bauble support for charms

### ISSUE THREAD

**Issue by ghost** [Darkhax-Minecraft/Dark-Utilities#119]
I think it would be great to be able to equip a charm (or more, with some sort of item to hold them) as a bauble in the charm slot, especially since not many mods use that slot.

**Comment by darkhax** [comment]
Baubles support was re-added in the latest update. This is fixed in the [latest alpha](https://minecraft.curseforge.com/projects/dark-utilities/files/2506687). If the file is not available for download, wait for Curse to approve it.
