### ISSUE TITLE
Suggestion : Your timer should react to a redstone signal next to it

### ISSUE THREAD

**Issue by mcdodge34** [Darkhax-Minecraft/Dark-Utilities#12]
So I'm discovering some parts of your mod right now and I've built your timer to control my tinkers construct smeltery and I was expecting to be able to turn it on and off with a redstone signal next to it but nope, doesn't react to a vanilla minecraft lever no matter where I put it, it doesn't stop your timer at all. Maybe a quick fix for your next build.

**Comment by darkhax** [comment]
Thank you for the suggestion, I will look into this.
