### ISSUE TITLE
Lore tags crash client when using them on dedicated server

### ISSUE THREAD

**Issue by C0rn3j** [Darkhax-Minecraft/Dark-Utilities#122]
DarkUtils-1.12.2-1.7.178.jar
MC 1.12.2
Forge 2529

1) Craft a Lore tag
2) Right click with the tag and write anything as lore
3) Click done - immediate desync and kick

https://paste.c0rn3j.com/?53d9d7904a9e4002#KeHPeV3USXZOZK4SUQXShhHuwr7cDu8N7eLnXBot+y8=

Error log

**Comment by darkhax** [comment]
Thanks for the detailed report. Unfortunately I can't seem to reproduce the error you are having. The file you linked shows that something is going wrong while trying to access a timer block from my mod. The timer issue seems to be that the timer block is somehow corrupted, or the client and server are not using the same version of Bookshelf. 

From what you described, you're also using the lore tag incorrectly. Right clicking a mob with a lore tag will not do anything. When you right click with a lore tag in hand the player is given a GUI for the lore tag which allows you to add some short text. The lore tag can then be combined with another item in the anvil to put the lore tag's text onto the tooltip of the other item.

**Comment by C0rn3j** [comment]
I've edited the reproduction steps, as involving an anvil is not necessary. 

Bookshelf-1.12.2-2.2.484.jar

Server and client should both have identical mods (I checked bookshelf though, it's identical).

This is the current list of mods running on the server - 

https://paste.c0rn3j.com/?dfe3e1e4ee997c5c#CHNuxRnb70ByR6zhKFOrf6MxjHnThLkR8XbblzeutzE=

I'll try reproducing in SP and checking if it happens in conflict with some other mod.

**Comment by C0rn3j** [comment]
As I can't reproduce it in SP, here's the current mods folder - 
https://cloud2.c0rn3j.com/s/tZie88TNp8jG6nc

If you want to try and track down which mods conflict on a dedicated server, you're free to.

If you don't wanna I'll likely end up doing so in a few days when I have HW that doesn't take ages to load everything.

**Comment by darkhax** [comment]
I've managed to reproduce in in a multiplayer world using just my mods. Will dig into this further.

**Comment by darkhax** [comment]
Okay, I think I got it. Features would load in a semi-random order using annotations. While this typically isn't an issue things like packets have IDs that are based on load order. So if the lore tag feature loads first on the client, and the timer feature loads first on the server, there will be miscommunication. Features are now set to load in a specific order, and I can no longer reproduce this.

**Comment by C0rn3j** [comment]
That was a very quick fix, thanks!

**Comment by C0rn3j** [comment]
Updated my mods and tested, it doesn't DC me anymore so I'm closing this issue.

Once again thanks for an extremely quick response!
