### ISSUE TITLE
Null Charm Doesn't Mantain Selected Blocks 1.12.2 - 1.7.181

### ISSUE THREAD

**Issue by Spiker985** [Darkhax-Minecraft/Dark-Utilities#124]
Once I have placed the blocks that I want to be voided, I press ESC or E to close the GUI. 

Trying to pick up the selected blocks actually yields the blocks, rather than them being voided

When I open the GUI again, the block slots are blank. There is only 1 NBT tag whether I have tried to place blocks in the GUI or not.

DarkUtils - 1.7.181
Forge - 14.23.0.2532

FTB Horizons 3 pack - 1.2.0

**Comment by darkhax** [comment]
I could not reproduce the issue. Testing in a client and server environment show that the item is being synchronized exactly as it should be. From your description, it sounds like something is interfering with the item. Possibly the server has a long delay, or the inventory is not synced.
