### ISSUE TITLE
[Feature request] Using wither dust on a plant prevents it from growing

### ISSUE THREAD

**Issue by TheDeviantCrafter** [Darkhax-Minecraft/Dark-Utilities#125]
There used to be a mod that let you craft "darkmeal" from nether warts. Holding it and right clicking on a plant would prevent it from growing. It only worked on vanilla crops, and now I can't find it anywhere.

I'd like to see wither dust get a similar function. When holding it in your hand and right clicking on a plant, that plant would then stop growing. Specifically, they wouldn't receive any growth ticks. The block itself, as well as its texture, wouldn't change. WAILA and similar mods should probably tell you that a plant is withered. Also, withered crops can't be affected by bone meal.

Some possible uses for this:

1. When terraforming, sometimes I like to have dirt close to grass. This would let me keep the dirt as dirt without using coarse dirt.

2. Keep standing vines from growing too long. They make nice tree decorations, but now when

3. Use partially grown plants as decorations.

4. Preventing yourself from accidentally bonemealing grass when you're trying to use bonemeal to grow a tree or make a tall Botania flower.

**Comment by darkhax** [comment]
I am not so sure about this, it's not a bad idea, but it's not really something I want to include as part of this mod.
