### ISSUE TITLE
[1.12.2] Charms not working with Baubles

### ISSUE THREAD

**Issue by PapiDimmi** [Darkhax-Minecraft/Dark-Utilities#126]
**Minecraft version**: 1.12.2
**Forge version**: 14.23.0.2531
**Dark Utilities version**: 1.7.182
**Baubles version**: 1.5.1

**Comment by 132ikl** [comment]
+1

**Comment by darkhax** [comment]
This is a duplicate of #119  

Baubles took so long to update that I removed support for it. Haven't had time to re-add the support.
