### ISSUE TITLE
[1.12.2] Server Crash on launch with 185 release.

### ISSUE THREAD

**Issue by kin0025** [Darkhax-Minecraft/Dark-Utilities#127]
Server crashes on launch with the latest release, downgrading to 181 fixes the problem. Clients launch perfectly fine on both versions.
[crash-2017-12-06_02.43.06-server.txt](https://github.com/Darkhax-Minecraft/Dark-Utilities/files/1531834/crash-2017-12-06_02.43.06-server.txt)

**Comment by xKnightGamingx** [comment]
Ran into this same prob aswell

**Comment by JoeSGT** [comment]
Same here
