### ISSUE TITLE
Player Trap JEI description has information for another item

### ISSUE THREAD

**Issue by Zsashas** [Darkhax-Minecraft/Dark-Utilities#128]
Looks like it's the Experience Monolith or something similar. All other traps are fine.

![2017-12-09_18 40 21](https://user-images.githubusercontent.com/6917535/33801468-b986a3b8-dd10-11e7-929f-4e8b4373e434.png)

**Comment by darkhax** [comment]
Thanks for reporting this. The first half of the description is correct, however it looks like I accidentally wrote the exp monolith description on the wrong line lol

**Comment by darkhax** [comment]
Thanks again for the report. This issue is fixed, and will be available once Curse accepts it.
