### ISSUE TITLE
Crash with chisel

### ISSUE THREAD

**Issue by Watchful1** [Darkhax-Minecraft/Dark-Utilities#13]
Trying to use a chisel block on a sneaky block, in this case a torch and a laboratory block, results in this crash.

http://pastebin.com/LakGmjGM

**Comment by darkhax** [comment]
Could you describe the situation in greater detail? I have tested using the same versions and am not able to reproduce the crash. Things like the exact variation and placement would be useful. This screenshot from my test has two of the right facing arrow designs with a sneaky torch in the middle. 
![image](https://cloud.githubusercontent.com/assets/2250798/19133140/05cc69f6-8b14-11e6-91da-c365fd45f33f.png)

**Comment by Watchful1** [comment]
![2016-10-05_17 56 31](https://cloud.githubusercontent.com/assets/1574415/19133219/23eb063e-8b25-11e6-877f-21218325a618.png)

Using dark utilities 1.1.4.86 and chisel 0.0.6.48. It looks like they've since taken down that chisel version. So maybe it was a bug on their side.

**Comment by darkhax** [comment]
Ah okay, that makes sense. I am using version 0.0.6.46. Misread your version number. Try again using that version of chisel, if it works this would indicate a bug in the newer issue.

**Comment by darkhax** [comment]
Going to assume this issue has been fixed. If not please let me know.
