### ISSUE TITLE
Client Crash with clicking outside the GUI with an item for the null necklace. 

### ISSUE THREAD

**Issue by KaneHart** [Darkhax-Minecraft/Dark-Utilities#130]
**Version:**
DarkUtils-1.12.2-1.8.187.jar

I was trying to figure out the necklace and click a block outside the inventory screen of it to like drop the item and boom it crashed my poor little client. 

[crash-2017-12-17_19.25.12-client.txt](https://github.com/Darkhax-Minecraft/Dark-Utilities/files/1566256/crash-2017-12-17_19.25.12-client.txt)

**Comment by darkhax** [comment]
This issue was fixed 5 days ago, but I forgot to close. Thanks again for the report!
