### ISSUE TITLE
Pearl Block recipe conflict - DU 1.7.181

### ISSUE THREAD

**Issue by xenoflot** [Darkhax-Minecraft/Dark-Utilities#131]
Hi,

The 2x2 unshaped recipe for Shulker Pearls conflicts with the (shaped?) recipe for turning Pearl Blocks into Pearl Bricks. Consequently, the Chiseled and Carved blocks can't be created either.

Perhaps change the Shulker Pearl recipe to require 4 Pearl Blocks in a + formation? That way you can preserve the 2x2 conversion between block types.

Cheers!

**Comment by darkhax** [comment]
https://github.com/Darkhax-Minecraft/Dark-Utilities/commit/166b2671b334c770998aa9a13d30a0f45375bceb
