### ISSUE TITLE
Enhancement request / suggestion for Sneaky blocks

### ISSUE THREAD

**Issue by xenoflot** [Darkhax-Minecraft/Dark-Utilities#132]
Hi,

I've been playing with Sneaky Blocks a bit today and I've noticed a few quirks.

1. The simple right-click to apply a new texture leaves them open to accidental re-texture either by a careless owner, or a visitor who isn't aware there are sneaky blocks around.
2. Since right-clicking is the normal mode of interaction for levers, and they normally work with a full or empty hand, they're especially prone to accidental re-texture or, if an incompatible block is in-hand, placement of the block.
3. Sneaky False Block and Sneaky Torch textures are ugly :D
4. Sneaky Pressure Plate texture hides that it's a full-height block.

May I suggest that the application of textures require a Ctrl+ or Shift+ right click? That would reduce the changes of accidental re-textures or accidental block placement.

It would also be nice if a stack of sneaky blocks could be textured by putting them in a crafting grid with the desired block. Not sure how easy that would be to code.

I'm no artist, but if you'd like, I can have a go at making new textures for the False Block, Torch and Pressure Plate.

edit: And perhaps add Sneaky Glass for situations where you want a sneaky block to permit light to pass through.

Cheers!

**Comment by darkhax** [comment]
Hello, thanks for your message. 

Blocks can not normally react to a sneak right click. This means that things like ctrl or shift will not actually work. It is possible to add a new keybind for them, but that is a convoluted solution. In the next update I am planning to add a sneaky key item, which allows the texture of a sneaky block to be locked. This would solve the issue you are having. 

I don't see why anyone would care about the sneaky block textures. You're not meant to look at the blocks in regular form for long periods of time, and having a black placeholder texture makes sense. 

Sneaky glass could be a nice feature. Same with crafting recipes to make things quicker.

**Comment by xenoflot** [comment]
Sneaky Key seems like a great idea.

Yes, improving the textures isn't necessary at all. Just something I noticed while playing around with things today and thought I'd mention it.

**Comment by Sewef** [comment]
Suggestion : craft a sneaky block with the target block to get the texture.
Something like Diaphanous Blocks (https://lumien.net/rtwiki/blocks/diaphanous-blocks/)

https://github.com/lumien231/Random-Things/blob/master/src/main/java/lumien/randomthings/block/BlockBlockDiaphanous.java

**Comment by Darkhax** [comment]
I am going to be redesigning how sneak blocks work for 1.13.2. Going to close this issue as it wont apply to the new version.
