### ISSUE TITLE
Blue Lore Tag recipe missing

### ISSUE THREAD

**Issue by xenoflot** [Darkhax-Minecraft/Dark-Utilities#134]
Hi,

I tested all the Lore Tag dye combinations today and found I was unable to create a Blue tag. Lapis creates a Dark Blue tag and Light Blue Dye creates an Aqua tag.

I also noted that the recipes aren't oredict'd as modded dyes didn't work.

Cheers!

**Comment by darkhax** [comment]
You're using an outdated version. 

lapis = blue
light blue = light blue
diamond = aqua

This recipe does use the oredict.

**Comment by xenoflot** [comment]
Thanks very much. I'll have the boss update our version.
