### ISSUE TITLE
Mobs not spawning on vector plates

### ISSUE THREAD

**Issue by LocoCubano** [Darkhax-Minecraft/Dark-Utilities#135]
So I have created a mob spawning room and am standing 32 blocks away from it, its completely dark but no mobs are spawning in it. I am on the Direwolf20 pack for 1.12. the floor is all vector plates leading to a hole in the center where the mobs drop onto diamond spikes.

I do know that if it was cursed earth beneath the plates the cursed earth mobs do spawn but standard spawns are not working,

**Comment by darkhax** [comment]
I take it you solved the issue? :p
