### ISSUE TITLE
Crash when placing monolith of experience

### ISSUE THREAD

**Issue by JoeSGT** [Darkhax-Minecraft/Dark-Utilities#136]
https://pastebin.com/uekGhZxW
when i place down monolith of experience and it start too suck up the EXP it crashes
My versions are
 darkutils - 1.8.186
forge-1.12.2-14.23.1.2581

**Comment by darkhax** [comment]
Thanks for the report, I will have a fix out soon.

**Comment by darkhax** [comment]
New version of Bookshelf is out which should fix this. CurseForge is out for the holidays, so you can download the update [here](https://maven.mcmoddev.com/net/darkhax/bookshelf/Bookshelf-1.12.2/2.3.516/Bookshelf-1.12.2-2.3.516.jar). If you still have issues with the monolith let me know and I will try to fix them.

**Comment by JoeSGT** [comment]
Thanks for the fast fix and happy holidays
