### ISSUE TITLE
Wither dust block is only craftable in a 3x3 crafting grid

### ISSUE THREAD

**Issue by taj1994** [Darkhax-Minecraft/Dark-Utilities#137]
I'm using version 1.7.181, and I'm not able to craft wither dust into blocks in my inventory, even though it's a 2x2 recipe.

![2017-12-29_23 41 28](https://user-images.githubusercontent.com/1844822/34451977-b5b259ca-ecf2-11e7-929e-a1ccc08d1b1e.png)
![2017-12-29_23 47 51](https://user-images.githubusercontent.com/1844822/34451978-b5cdc35e-ecf2-11e7-9640-ec24e5fb62b8.png)

**Comment by darkhax** [comment]
Thanks for the report!

**Comment by darkhax** [comment]
Sorry for the late response. This issue has now been fixed.
