### ISSUE TITLE
Mob Filter Fire Res and Ancient Golem

### ISSUE THREAD

**Issue by WilxGaming** [Darkhax-Minecraft/Dark-Utilities#138]
Modern Skyblock 3 v3.1.1.1
DarkUtils-1.12.2-1.8.192.jar
embers-0.230.jar
forge-14.23.2.2611

Ancient Golem is Fire Resistant, when walking over Mob Filter Fire Resistant they fall through but their head gets stuck and they suffocate. I was using the filter in a mob tower to drop them into the void because they could survive the fall. They take a long time to die like that. There was over 12 of them in a 2x1 area suffocating.

**Comment by darkhax** [comment]
What do you mean by their heads getting stuck? Like the pit is not deep enough for them to fall, or the heads wont fall through the block?

**Comment by WilxGaming** [comment]
They are 2 blocks high. The top half is the filter, bottom half is dangling below the filter. There are 2 filters side by side. Nothing above or below the filters. It was meant for them to drop down a 2x1 shaft all the way to the void. So yes they seem to be stuck in the filter suffocating.

**Comment by darkhax** [comment]
Can you post a screenshot of the mob just so I can see ? Like preferably from an angle?

**Comment by WilxGaming** [comment]
![javaw 2018-02-10 00-29-51-026](https://user-images.githubusercontent.com/35704610/36058882-f88ca70a-0df9-11e8-873f-118e4434311b.png)
![javaw 2018-02-10 00-29-44-025](https://user-images.githubusercontent.com/35704610/36058884-fc08e6aa-0df9-11e8-8212-92c1c4f95f9b.png)

There are a lot of them. They keep bouncing in and out. They are no longer dying. I broke the shaft so you could see better.

**Comment by jmcaffee** [comment]
I'm having the same issue. At first I though they were getting hung up in the 2x1 shaft, so I expanded the shaft to 2x2 only to see another bunch of ancient golems dangling from their heads.

It seems the heads will not fall through.

**Comment by darkhax** [comment]
This issue is very confusing. It's almost as if the head is a separate entity. I am planning to do another round of updates to this mod soon so I will update everyone with what I find in the next day or two.

**Comment by darkhax** [comment]
After doing some further testing, I am able to get this working with with just the mods you listed. This issue is being introduced by another mod in the pack. If you have any mods which add something like custom hitboxes for the head or arms, I would start there.
