### ISSUE TITLE
Mobs don't spawn on Vector Plate

### ISSUE THREAD

**Issue by tksnt** [Darkhax-Minecraft/Dark-Utilities#14]
Mobs don't spawn on Vector Plate. After following changes, mobs spawn properly and plates keep its functionality.

```java
    @Override
    @Nullable
    public AxisAlignedBB getCollisionBoundingBox(IBlockState blockState, World worldIn, BlockPos pos)
    {
        return NULL_AABB;
    }
    
    @Override
    public boolean isFullCube (IBlockState state)
    {
        return false;
    }
    
    @Override
    public boolean isOpaqueCube (IBlockState state)
    {
        return false;
    }
```

**Comment by darkhax** [comment]
Thank you for reporting this issue and providing a solution. I will implement this and text in my private dev environment before pushing a fix.

**Comment by tksnt** [comment]
Thank you very much! I verified on latest master branch!

**Comment by Zutaradimus** [comment]
I can see that this has been closed but sadly this issue is occurring for me. I am using the most recent release for Dark Utilities and Bookshelf due to the dependencies. I'm kind of at a loss on this one. This is occurring on the FTB Direwolf20 Mod Pack available through Curse.

**Comment by tksnt** [comment]
Hi Zutaradimus,

It is working for me on DW20 pack version 110-1.6.1-1.10.2. For verification, I tried below.

1. Create a new world with super flat bedrock.
2. Build a 6x6 platform with stones.
3. Place vector plates on it.
4. Watch the platform from the distant location.

If your DW20 installation works with above steps, then I guess your mob firm has another problem which prevents mob spawn.

**Comment by gp3t1** [comment]
I have a similar issue but it only happens when i'm far from my farm >100 blocs. It's a basic curse earth mob farm(chunk loaded) with vector plates with a good output when i'm around(hundreds items/minute). But as soon as i left the area, the outputs drop to 0.0000.
I tried removing some vector plates around one of my mob masher and, once i got back to my storage area(~1000blocs away) i could observe some occasional drops. So i think that in some way the vector plates might prevent spawn or even despawn mobs, at least for cursed earth farms when no player is around.
modpack details:
[Sky Factory 3] 3.0.8 Beta, single player 
[Dark Utilities] 1.1.7.112

**Comment by darkhax** [comment]
@gp3t1 Mob spawning is based on the players position. Chunk loading will do nothing if there isn't a player nearby.

**Comment by gp3t1** [comment]
In extra utilities, cursed earth do spawn mobs even if the player is far away. I'll continue my research and let you know if I can relate this problem to the vector plates with hard evidences.

**Comment by Zutaradimus** [comment]
Okay, I have figured out the issue. I was using an older version of literally every mod on my list. Once I updated everything it all started working. My most recent update was a few days ago. Before that I had to try several different things just to get mobs to spawn. Glad it was solved with a simple update, keep being an awesome folks and thanks for all the info. Sorry for the lack of responses lol.

**Comment by yunumberjuan** [comment]
Okay, so, what the hell is that code (?) that @tksnt wrote and how do I implement it into Dark Utilities? I can't seem to get any monsters to spawn on vector plates and the oldest versions of my mods are only about 6 months old. I'm a programming virgin.
