### ISSUE TITLE
ChiselsAndBits conflict

### ISSUE THREAD

**Issue by ggblbl** [Darkhax-Minecraft/Dark-Utilities#141]
In my serverlog it says "[chiselsandbits]: Unable to determine blocks eligibility for chiseling" for some of the blocks in the mod.
I read up on the error (https://github.com/AlgorithmX2/Chisels-and-Bits/issues/49) and it seems it can't be fixed by @AlgorithmX2.
These are the blocks:
net.darkhax.darkutils.features.sneaky.BlockSneaky attempted to load net/minecraft/client/particle/ParticleManager

**Comment by darkhax** [comment]
Sneaky blocks are tile entities and don't have textures, so you should not be able to use them in chisel and bits blocks.

**Comment by ggblbl** [comment]
That's what I figured, but still ChiselsAndBits seems to think it needs to make the sneaky block a chiseled version.

**Comment by darkhax** [comment]
I will reach out to the dev of that mod and see what I can do to stop that.

**Comment by darkhax** [comment]
I have pushed out this experimental fix for your issue. Please let me know if it fixed your issue. https://minecraft.curseforge.com/projects/dark-utilities/files/2539462

**Comment by ggblbl** [comment]
It seems to have done the trick!
It's not in the humongous list of caught exceptions anymore!
Thanks!

**Comment by darkhax** [comment]
Thanks for confirming the fix :D
