### ISSUE TITLE
Ender tether broken texture

### ISSUE THREAD

**Issue by Froggy800** [Darkhax-Minecraft/Dark-Utilities#142]
Starting from version 1.12.2-1.8.198 the ender tether doesn't render correctly; if it's placed against a wall it becomes invisible, while if it ìs placed on the ground it appears as a missing texture block.
![2018-03-16_16 40 47](https://user-images.githubusercontent.com/25703114/37530324-2b4aaa6e-2931-11e8-899d-2a8557db305d.png)
Tested on Forge version 14.23.2.2613 and no other mods beside Bookshelf.

**Comment by darkhax** [comment]
Thanks, could you get a closer screenshot of the text on the block?

**Comment by Froggy800** [comment]
Thanks to you! Here you go.
![2018-03-16_18 56 51](https://user-images.githubusercontent.com/25703114/37536761-6f44300c-2943-11e8-9786-0c070207b5c7.png)
P.S.: The previous screen was mainly to show the bounding box of an ender thether.

**Comment by darkhax** [comment]
Thanks for the new picture. I will look into getting this fixed.

**Comment by darkhax** [comment]
This issue should now be fixed in the latest version. Thanks again for the report.
