### ISSUE TITLE
[1.11] Sneaky blocks broken?

### ISSUE THREAD

**Issue by Terpo** [Darkhax-Minecraft/Dark-Utilities#146]
Bookshelf-1.11.2-2.0.0.388.jar
DarkUtilities-1.11.2-1.2.0.147.jar
with JEI on Forge v13.20.1.2588

https://i.imgur.com/ybP1lh8.png

Maybe I understand something wrong but: I do place down the sneaky block and after that I am right clicking with another block on it right? Right click with basic clean stone does nothing, and there is nothing in the log about it. (no crash, no error, no warning)
This are all sneaky blocks placed down after each other.

**Comment by darkhax** [comment]
Yes, this is a bug. It was not reported until the mod had already moved to 1.12. If you want to use the sneaky blocks in 1.11 you can revert to [this](https://minecraft.curseforge.com/projects/dark-utilities/files/2409028) version.

**Comment by Terpo** [comment]
Do you know if anything else could break between 134 and 147? If not I will give it a try :).
