### ISSUE TITLE
Shift clicking blocks into null charm causes client hard run and eventual crash

### ISSUE THREAD

**Issue by mccoole** [Darkhax-Minecraft/Dark-Utilities#147]
Version 2.1.7.181 in the Engineer's Forest 3 modpack.  I shift clicked a cobble stone block into the null charm and the client went into a hard run, locked up and eventually ran out of memory and crashed.

**Comment by darkhax** [comment]
This issue was fixed roughly 6 months ago, the version you are using is very outdated.
