### ISSUE TITLE
[Question] Monolith of Spawning

### ISSUE THREAD

**Issue by unclekakarot** [Darkhax-Minecraft/Dark-Utilities#148]
Is there any options for the monolith of spawning or is there like a range it has?

**Comment by darkhax** [comment]
Monoliths do chunk based effects.

**Comment by unclekakarot** [comment]
So it only spawns in the chunk it's in?

**Comment by darkhax** [comment]
Yes, monoliths will only affect the chunk they are in, and effect the entire height. y= 0 to 255.
