### ISSUE TITLE
Missing Rings?

### ISSUE THREAD

**Issue by SummitSummit** [Darkhax-Minecraft/Dark-Utilities#15]
I'm confused.  Were the rings removed?  I'm on version DarkUtilities-1.10.2-1.1.4.86.  First time I've played with Dark Utilities and the info everywhere talks about these rings that buff enchantments which I can not find in JEI, nor in any of the dungeon chests I've looted.

**Comment by darkhax** [comment]
The rings were removed in 1.10.2. They will likely be re-added in another version.

**Comment by darkhax** [comment]
The rings have been re-added in the latest alpha version. They are still being tested and may be removed if they get a negative response, or I find that I don't like them.
