### ISSUE TITLE
Timer does not add zero from num pad

### ISSUE THREAD

**Issue by Cyberwolfent** [Darkhax-Minecraft/Dark-Utilities#150]
When using the number pad to change the timer setting it does not accept the zero from the Num pad.  It only adds it from the numbers above the qwerty keys

**Comment by darkhax** [comment]
Sorry for taking forever with this issue, I have been very busy. Sewef is the one who actually fixed this issue though, so all credits to them. I don't know if you still care about this issue, but if you update Bookshelf to the latest version this issue should be resolved. If not let me know and I can look into it again.
