### ISSUE TITLE
Gluttony charm does not interact with the lunch box from spice of life

### ISSUE THREAD

**Issue by Owis54** [Darkhax-Minecraft/Dark-Utilities#151]
Issue: Gluttony charm does not interact with the lunch box

Is it Repeatable?: yes just put food in the lunch box, equip the gluttony charm and it will not insta-eat 

Playing FTB Continuum 1.1.0

**Comment by darkhax** [comment]
The lunch box is not actually a food item, Spice of Life seems to be using a core mod to hack the vanilla game to allow it to be edible. While it would be nice to have support, I can't add support in a reasonable way at this time.

**Comment by darkhax** [comment]
The lunch box is not actually a food item, Spice of Life seems to be using a core mod to hack the vanilla game to allow it to be edible. While it would be nice to have support, I can't add support in a reasonable way at this time.
