### ISSUE TITLE
Sneaky Vector Plate

### ISSUE THREAD

**Issue by plunginghornets** [Darkhax-Minecraft/Dark-Utilities#152]
I love using vector plates as a method of quick travel around my base. No ugly moving conveyors, no getting in a minecart, just a part of the floor that pushes me along. But having a bunch of colored arrows on the floor isn't especially pretty. Can we get a version of the Vector Plate that accepts another block's texture?

**Comment by darkhax** [comment]
This is possible to add, however I don't really know if I want to open this can of worms. I've already had people ask for sneaky mob filters, and sneaky trap blocks and so on. It is something I will definitely have to think about more.

**Comment by joernott** [comment]
Maybe, you could simply create vector plates which operate one level above the plate itself. Thus, players could place any kind of block on top of them.

**Comment by Jkosio23** [comment]
Say, plates that can go on the ceiling and effect the upper surface of the block they're placed on?

**Comment by Sewef** [comment]
> Say, plates that can go on the ceiling and effect the upper surface of the block they're placed on?

Let's talk about Vector Blocks to do this, because plates underground would render blocks uselessly.

**Comment by Darkhax** [comment]
I am going to be redesigning how sneak blocks work for 1.13.2. Going to close this issue as it wont apply to the new version.
