### ISSUE TITLE
Add button to GUI to turn off the timer.

### ISSUE THREAD

**Issue by Cyberwolfent** [Darkhax-Minecraft/Dark-Utilities#153]
You should add a way to turn the timer off.  Say setting it to 0 doesn't allow it to run.  This comes in handy when you need to make changes to whatever the timer is hooked up to without having to break the transmission line from the timer.

**Comment by darkhax** [comment]
You can turn the timer off by applying a redstone signal to it. I will think about adding a gui option too.
