### ISSUE TITLE
crash on startup

### ISSUE THREAD

**Issue by matyklugDebbuged** [Darkhax-Minecraft/Dark-Utilities#154]
https://paste.dimdev.org/udehijatub.mccrash
1.12.2

**Comment by darkhax** [comment]
This is a very weird crash, it's acting as if you don't have baubles installed. I would recommend uninstalling baubles and Dark Utilities, and then re-downloading them from the official CurseForge pages.

**Comment by matyklugDebbuged** [comment]
i download dark utils from curseforge, and baubles from curse launcher. btw if i disable rockhounding, it work.

**Comment by darkhax** [comment]
This seems like a weird load order issue. I put out a new version that forces loading to happen after baubles. If this doesn't fix it I guess rockhounding is mess with stuff. https://github.com/Darkhax-Minecraft/Dark-Utilities/commit/96d8ac5fe36e3279ff4a7de02a38bfa4847b2b01
