### ISSUE TITLE
Suggestion: Filter for specific mob type

### ISSUE THREAD

**Issue by joernott** [Darkhax-Minecraft/Dark-Utilities#156]
So far, I have not found any mod which allows for detailed mob sorting (e.g. filter out villager zombies from regular zombies, sheep, pigs and cows). I use your mob filters quite regularly for filtering out baby animals, so I'd like to suggest the introduction of some kind of mob filter, where you cold explicitly filter for mob types. Maybe the player could use a syringe (like the one in RFTools) to take samples from mobs which are then inserted into the filter to configure it for that mob.

**Comment by Darkhax** [comment]
I am going to be changing how the filter blocks work in 1.13.2, and this change will allow for greater control over how things work. Going to close this issue for now as it's no longer relevant.
