### ISSUE TITLE
Sneaky blocks not taking on textures

### ISSUE THREAD

**Issue by lunchboxxx19** [Darkhax-Minecraft/Dark-Utilities#160]
using minecraft version 1.11.2, forge version 13.20.1.2386 and dark utilities version 1.2.0.147 the sneaky blocks dont take on any textures when right clicked

I am trying to apply a dirt block to a sneaky torch. but cobblestone and all other stones dont seem to work either

**Comment by darkhax** [comment]
Does the sneaky block look like black stone? If not, you're using a broken version and should go back a few versions. I am currently focusing on newer versions of the game and no longer support any outdated versions.
