### ISSUE TITLE
Mobs spawn inside of Sneaky False Blocks

### ISSUE THREAD

**Issue by DMBuce** [Darkhax-Minecraft/Dark-Utilities#161]
In the Enigmatica 2: Expert Skyblock pack (MC version 1.12), I'm using Sneaky False Blocks (SFB) as doorways in a well-lit corridor. Since SFBs don't have a collision mask and don't transmit light, mobs spawned inside.

As a workaround I placed glowstone below the SFBs so that mobs can't spawn, but it's a bit surprising that an SFB placed in a well-lit area can spawn mobs inside it. So I'm wondering if that's intended behavior or not.

**Comment by darkhax** [comment]
Thanks for reporting the issue. This was the intended behavior when I wrote the code for this block, however you're right that it doesn't really make sense. I am going to merge Sewef's PR that fixes this.

**Comment by Sewef** [comment]
Don't be too quick, it doesn't work :'D
I guessed you'd test before marging, as I wasn't on my own computer. I'm currently tracking why mobs keep spawning in skeakyghost.
