### ISSUE TITLE
[1.12.2] Focus Sash only accounts for the original damage taken. It also doesn't take into account for any Damage Reduction or Absorption.

### ISSUE THREAD

**Issue by Z-Tunic** [Darkhax-Minecraft/Dark-Utilities#168]
Minecraft: 1.12.2
Forge: 14.23.5.2795

Mods: 1
*DarkUtils-1.12.2-1.8.219*

-----

Was originally a comment before... but been leaning towards it being a bug. Anyway... to quote my comment about the Focus Sash...

>*There's an object that deals 48 damage via magic, or rather... /effect instant damage 3. With my health at 20... due to the way the sash works. I take 19 damage, leaving me with 1 health. Now... if you have armor on & such, you can reduce the damage value that the sash sets, so using the same setup but wearing Diamond Armor with Protection IV x4, that damage from the sash gets cut down from 19 to 6 but only because my health is full. Magic bypasses armor so I went with the Protection IV way.*

>*Without the sash I take 17 damage which... isn't enough to kill me as I'll be left with 3 health. My guess is that it's taking into account of the full 43 damage rather than the reduced damage which without any form of damage reductions I'll be taking the full 43 damage.*

 >*Now say I have 20 Absorb due to a powerful potion effect or a mod that grants you some sort of shield, using the same setup at full health + the diamond armor with the protection + sash... 6 of that damage is dealt to my absorb. Because I have 20 Absorb... I can survive 4 instant kills as the 4th hit will affect my health, then I will take the 17 damage on the 5th hit.*

 >*I'm just wondering if the Focus Sash is suppose to be doing this with ignoring damage reductions & absorb leading to surviving multiple instant kills. It tends to be more noticeable with mods that allow you to scale your health/absorb alongside damage sources being scaled. Like one can run with 20 Health + 100 Absorb and they'll be able to survive many instant-kills from something that deals 10000 magic damage but it'll be reduced to 19 due to max health being at 20 and further reduced due to armor/protection/other, if 6 damage that's 17 instant-kill hits blocked with the 18th hit being fatal.*

-----

To add onto this...

Using a few mods such as Scaling Health & Cyclic which allows me to altar max health... I can lower my maximum health from 20 to just 2 and with a good Absorption Potion Effect or using a mod called Natural Absorption which grants you a rechargeable absorption shield... I am pretty much invincible if I have a high enough Absorption as the Focus Sash will reduce all damage to 2 due to my max health and further reduce it if I have Protection IV & other defense factors. Heck, even damage sources that should outright kill you will only at most deal 2-3 damage due to the Sash and if having like 100+ absorption... that's quite a number of instant kills that I'm saved from.

*EDIT*
Apparently with Scaling Health & Cyclic, I can have exactly 1 or less Max Health... which means that as long as I have the Focus Sash I cannot die as the damage dealt will always be 0. Not even /kill can do anything.

**Comment by Sewef** [comment]
I read the Focus Sash code and tried to fix that using native functions `applyArmorCalculations`, `applyPotionDamageCalculations` and `getAbsorptionAmount`.
If everything is cool, it applies armor and potion effect to the damage, check if it's more than (maxHealth+absorption) and if so applies a (maxHealth-1) damage.

**Comment by Z-Tunic** [comment]
Would that account for the Protection enchantments?

**Comment by Sewef** [comment]
> Would that account for the Protection enchantments?
I don't know and I can't find the right informations right now (I'm not in my dev env...). I'll check this ASAP.

> The Focus Sash shouldn't work if the player somehow got a Max Heath of 1 as they pretty much become invincible since maxHealth-1 would be 0 damage at 1/1 Health as long as they have it.
Well, a maxHealth (including absorption) is pretty uncommon XD
I'll add a condition

**Comment by Sewef** [comment]
Meh. I keep trying but `applyArmorCalculations` and `applyPotionDamageCalculations` are protected float. I haven't deal with those for a while :'D

**Comment by Sewef** [comment]
@Z-Tunic As your testing environement looks more advanced than mine, could you test this build? I experimented a little but I can't do more atm.

https://www.dropbox.com/s/ch1alx1cpvgpx03/DarkUtils-1.12.2-1.8.0.jar?dl=0

**Comment by darkhax** [comment]
The armor and potion issues are definitely a bug, and I am surprised that Forge doesn't already account for those. As for the half a heart max health issue, I don't see that as a bug. While that's definitely a very powerful combination, it's not possible to obtain under standard conditions, and once the above fixes have been applied it actually leaves the player in a very vulnerable state. You would have to have half a heart while wearing no armor and having no potion effects, which leaves you vulnerable to many of the weapons in other mods. To help make this less of an issue, I plan to make the half a heart thing configurable (enabled by default), along with adding durability to the sash, and an exception to allow void damage to kill the player.

**Comment by Z-Tunic** [comment]
Testing Build...

The Player now dies with 1/1 Health +Sash & 0/0 Health + Sash, which is good as they're no longer immortal. Absorption is accountable even with 1/1 Health or 0/0 Health as well as Armor & Protection. Void damage doesn't trigger the Sash so falling out of the world & /kill works as intended.

**Comment by Sewef** [comment]
> The armor and potion issues are definitely a bug, and I am surprised that Forge doesn't already account for those.

Forge has a `applyArmor` method that recreate the `protected float applyArmorCalculations` method from `EntityLivingBase`, but there's no `protected float applyPotionDamageCalculations` (calculation from Potions and Enchantment // magic) alternative :(

**Comment by Sewef** [comment]
@Z-Tunic 
> Just wondering... but is it intended for the Sash's set damage value to be reduced by defense factors like Armor, Protection, etc.?

Are you talking about my patch (where I [tried to] made damage absolute) or the current official build?

**Comment by Z-Tunic** [comment]
@Sewef 
It happens in the official build as well as the test build.

**Comment by Sewef** [comment]
@Z-Tunic 
Ahem.
It looks like Absolute damages can bypass Enchantment and Potion effects, but not armor.
Grmbl.
I set the `damageBypassesArmor` flag. New test build after work c:

**Comment by Sewef** [comment]
@Z-Tunic 
TAKE THAT.
https://www.dropbox.com/s/ch1alx1cpvgpx03/DarkUtils-1.12.2-1.8.0.jar?dl=0

**Comment by Z-Tunic** [comment]
@Sewef
OBJECTION.

Looks all good now. I guess Terrasteel/Flux Armor had a high armor value than what it visually shows on the armor bar which is perhaps why I was seeing such a massive damage reduction with the Absolute Damage in my survival world. By massive... Scaling Health is added on that world and I have damage sources scaled depending on it's difficulty.

**Comment by Sewef** [comment]
@Z-Tunic 
https://github.com/ArtixAllMighty/Rpg-Inventory-2016/blob/master/src/main/java/subaraki/rpginventory/handler/JeweleryEffectsHandler.java#L115
RPG Inventory's Emerald Gloves doesn't care about AbsoluteDamage.

https://github.com/Tamaized/AoV/blob/1.12/src/main/java/tamaized/aov/common/events/AttackHandler.java#L72
Angel of Vengeance's ShieldOfFaith too.

I don't know if it would be better to ask mod authors to add the Absolute behavior or find a way to bypass this in the Focus Sash code.

**Comment by Sewef** [comment]
Hey, let's be smart.

> LivingDamageEvent is fired just before damage is applied to entity.
At this point armor, potion and absorption modifiers have already been applied to damage - this is FINAL value.
Also note that appropriate resources (like armor durability and absorption extra hearths) have already been consumed.
This event is fired whenever an Entity is damaged in EntityLivingBase.damageEntity(DamageSource, float) and EntityPlayer.damageEntity(DamageSource, float).

I trashed everything and added a `@SubscribeEvent` on `onLivingDamage`.

**Comment by Z-Tunic** [comment]
That SubscribeEvent will handle any kind of damage reduction now, correct?

**Comment by Sewef** [comment]
It should, yea, as it's the damage amount with every modifier!

**Comment by Z-Tunic** [comment]
Alrighty. If you still want me to test it, let me know.

**Comment by Sewef** [comment]
I'll give you another test build asap ;)

**Comment by Sewef** [comment]
@Z-Tunic 
Mgrabblblblbl
https://www.dropbox.com/s/ch1alx1cpvgpx03/DarkUtils-1.12.2-1.8.0.jar?dl=0
Totally untested.

**Comment by Z-Tunic** [comment]
*Testing build...*

Focus Sash now accounts for modded damage reductions by the looks of it, no matter what I'll be left with exactly 1 HP if enough damage was done for a KO blow.

I had modded damage reductions from...

Level Up! Reloaded - Iron Skin Ability
*+5% Damage reduction per level, up to +50% at level 10 which is the max.*

RPG Inventory - Emerald Gloves & Cloak with Emerald Defense Incrustation II
*Gloves is a +20% Damage Reduction but I dunno how much for the Cloak.*

Angel of Vengeance - Shield of Faith
*+50% Damage Reduction when spell is in effect.*

Looks like everything is good.

**Comment by Sewef** [comment]
Yeay \o/
@darkhax Can you merge my PR please? ^_^

**Comment by darkhax** [comment]
Awesome :)
