### ISSUE TITLE
Suggestion-Hide Sneaky Blocks from Waila.

### ISSUE THREAD

**Issue by WenXin20** [Darkhax-Minecraft/Dark-Utilities#17]
Waila, The One Probe, and similar mods easily give away that the block is a sneaky block.

**Comment by darkhax** [comment]
The sneaky blocks are already hidden in Waila. The player who placed the sneaky block can still identify that it is a sneaky block, to help them keep track of it, but other players will see the held block.

**Comment by WenXin20** [comment]
Ok, thanks, I didn't realize that.

**Comment by darkhax** [comment]
If I get around to adding TOP support, I will be sure to add this. Will leave open for now.

**Comment by darkhax** [comment]
Given how much trouble TOP has been giving me, I no longer plan to add support at this time.
