### ISSUE TITLE
Connected textures don’t work with sneaky blocks

### ISSUE THREAD

**Issue by Dimentive** [Darkhax-Minecraft/Dark-Utilities#176]
Connected textures do not work with sneaky blocks, which defeats their purpose when using blocks with connected textures like I am here.

![2019-04-01_12 25 05](https://user-images.githubusercontent.com/34230933/55321206-5d9f2e80-5479-11e9-97fb-be5221efcc27.png)

The four blocks that don’t connect are sneaky false blocks.

#### Versions

* Modpack: [Enigmatica 2](https://minecraft.curseforge.com/projects/enigmatica2) (v. [1.63a](https://minecraft.curseforge.com/projects/enigmatica2/files/2691579))
* Dark Utilities: 1.8.224
* Bookshelf: 2.3.577
* Minecraft: 1.12.2
* Forge: 14.23.5.2781
* OptiFine: Yes

**Comment by Darkhax** [comment]
This is a known issue, and it's unfortunately not something I can realistically fix on my end. IIRC the chisel devs said they were working on a fix but I haven't heard anything for a while now.
