### ISSUE TITLE
World crashing when loading

### ISSUE THREAD

**Issue by cxav12** [Darkhax-Minecraft/Dark-Utilities#178]
Hello, my world is crashing upon loading. Here is the error log:

https://paste.feed-the-beast.com/view/d70c26c3

Backstory: While playing the FTB Builder's Paradise pack, I went to ore excavate blue leaves from a tree (forgot the name of the tree but it's the one that spawns in the magic biome) with a tinkers mattock with silky jewel attached to it. As soon as I hit the excavate button, my world crashed. 

I posted this issue on the FTB Builder's Paradise github and was told I could get help restoring my world here. Any help would be greatly appreciated!

**Comment by Sewef** [comment]
It seems to be a Forestry issue.
For your problem, I guess you can try to edit your inventory to remove the
guilty items and remove the drops with mcedit.

**Comment by Darkhax** [comment]
Thanks for the report. Looking at your crash log, there is no relation to Dark Utilities. The issue seems to be with Forestry.
