### ISSUE TITLE
Rustic mod; grape leaf block causing crash

### ISSUE THREAD

**Issue by Lectorel** [Darkhax-Minecraft/Dark-Utilities#179]
(Was routed here by a moderator on FTB-Builders-Paradise, am otherwise clueless. Please have patience with me.)

Modpack: FTB Builder's Paradise   
Modpack Version: 1.3.0
Issue: Rustic grape leaf block is generated, and immediately there's CCL exception error and the game crashes
Link to Log or Crash File Paste: https://paste.feed-the-beast.com/view/9058fe1d
Is it Repeatable?: Yes. World now crashes on load-up.
Mod/s Affected: Rustic
Attempted Solutions: changed settings of forge.cfg to remove erroring entities. World loaded, but crashed immediately afterwords.

**Comment by Darkhax** [comment]
Did you mean to post this on the Rustic issue tracker? This is the issue tracker for Dark Utilities, which is not involved with this crash, it's also not in the pack you are using.
