### ISSUE TITLE
[bug]Shulker pearl dupe

### ISSUE THREAD

**Issue by Tsukiumy** [Darkhax-Minecraft/Dark-Utilities#18]
v 1.1.5.91
when you craft a pearl block and convert it back, you will get 4x more, its returning 4 per block, but the crafting recipe giver 4 per 4 pearl.

**Comment by darkhax** [comment]
Thanks for reporting. Tempted to leave this in, given how hard it is to collect shulker pearls lol. I may remove back crafting all together and just increase the amount of blocks the recipe crafts.

**Comment by darkhax** [comment]
I fixed this issue by changing the recipe. The recipe now requires 8 pearls and an end stone. It now creates 32 rather than 8. You can also now exchange 4 blocks for one pearl.
