### ISSUE TITLE
Crafting recipe for Sleep Charm only works with white beds

### ISSUE THREAD

**Issue by Wxrlds** [Darkhax-Minecraft/Dark-Utilities#181]
JEI shows this recipe for the Sleep Charm:
![grafik](https://user-images.githubusercontent.com/42120270/66272068-506a5e80-e865-11e9-9d0b-90417254139d.png)
It's expected this recipe should also work but it doesn't
![grafik](https://user-images.githubusercontent.com/42120270/66272071-6710b580-e865-11e9-9628-20b1716c72e5.png)

Mod-Version: 1.8.226
Minecraft: 1.12.2

**Comment by Darkhax** [comment]
This is an issue with Bookshelf. It has been fixed there. https://github.com/Darkhax-Minecraft/Bookshelf/commit/1d281800d5a5b8f92989c238663b7e614007d136
