### ISSUE TITLE
Glass Renders Incorrectly Underwater

### ISSUE THREAD

**Issue by WenXin20** [Darkhax-Minecraft/Dark-Utilities#185]
`Minecraft v1.14.4`
`Forge v28.1.90`
`Dark Utils v2.0`
- Glass will display flowing water on its sides when placed underwater.
- Item Grate & Ender Hopper was missed and can't be waterlogged.

**Comment by Darkhax** [comment]
Thanks for reporting this issue. Both should be fixed in the new snapshot on CF. The glass blocks should also now affect beacon block colors.

**Comment by WenXin20** [comment]
I also recently found out that Crucibles and Filter blocks also render with flowing water down their sides when placed underwater.

**Comment by Darkhax** [comment]
As those are not glass blocks they will have to wait for https://github.com/MinecraftForge/MinecraftForge/issues/6319 to be addressed.
