### ISSUE TITLE
Crash w/ Ender Hopper

### ISSUE THREAD

**Issue by WenXin20** [Darkhax-Minecraft/Dark-Utilities#187]
`Minecraft v1.14.4`
`Forge v28.1.92`
`Dark Utils v2.0.3`

I got this crash after shift-right-clicking the ender hopper while it was underwater.
Here's the [Crash Report](https://gist.github.com/WenXin20/2d55601d5d728af2a13d429b4f65b864).

**Comment by Darkhax** [comment]
Thanks for the report, the issue has been fixed.
