### ISSUE TITLE
[1.14.4] Game Freezes when placing a Wither Slime Crucible

### ISSUE THREAD

**Issue by ToMe25** [Darkhax-Minecraft/Dark-Utilities#188]
When i place a Wither Slime Crucible into any World the game just Freezes.
It says Stopping server but never finishes that.

Versions:
Minecraft: 1.14.4,
Forge: 28.1.102,
Bookshelf: 6.2.60,
DarkUtilities: 2.0.7

Latest.log: https://pastebin.com/FaLwtvNe

**Comment by Darkhax** [comment]
Do you still have this issue if you use Bookshelf 6.2.65?

**Comment by ToMe25** [comment]
no it doesn't, i just don't know how i missed that as i downloaded the most recent version i could find earlier today and now it says that one is two days old...

**Comment by Darkhax** [comment]
Curse is a bit stupid with how they do latest versions. Latest is usually the latest version marked as a full release and not a beta or an alpha. I forgot to mark 6.2.65 as a full release so I changed it after I saw this issue. So that's likely why it changed.

**Comment by ToMe25** [comment]
That makes sense, thanks
