### ISSUE TITLE
[1.14.4] Player Traps cause a server crash upon killing a Pillager / Vindicator wielding a banner.

### ISSUE THREAD

**Issue by Vaelzan** [Darkhax-Minecraft/Dark-Utilities#191]
Player traps have been causing a server crash upon killing Pillagers and/or Vindicators that happen to be holding a banner. I believe the issue is due to the Bad Omen debuff being applied to the fake player, causing a null pointer exception in ServerPlayerEntity's onNewPotionEffect method.

I suspect that this may ultimately be a Forge issue, where the FakePlayer class needs to override a couple more methods to prevent things like this occurring, but so far I've noticed only Dark Utilities triggering this crash so I'm reporting it here for awareness (and just in case I'm wrong about it being a Forge issue).

Crash Report Pastebin: 
https://pastebin.com/zDGjeY8t

(in the Pastebin, func_70670_a is onNewPotionEffect)

**Comment by LlubNek** [comment]
Got the same crash with a zombie.  I might have had bad omen myself but I doubt that had anything to do with it.

[latest.zip](https://github.com/Darkhax-Minecraft/Dark-Utilities/files/3961696/latest.zip)
[crash-2019-12-13_11.15.45-server.txt](https://github.com/Darkhax-Minecraft/Dark-Utilities/files/3961705/crash-2019-12-13_11.15.45-server.txt)

**Comment by Darkhax** [comment]
Thanks for the report. This is indeed a forge issue and I have forwarded it to them here. https://github.com/MinecraftForge/MinecraftForge/issues/6358 

I may be able to apply a temporary fix on my end for this issue, however I think a forge update may be best. We will see how that issue plays out.
