### ISSUE TITLE
[1.14.4] Mobs cannot spawn on Vector Plates

### ISSUE THREAD

**Issue by NielsPilgaard** [Darkhax-Minecraft/Dark-Utilities#193]
Mobs are unable to spawn on Vector Plates, despite the description stating they should be able to.
Screenshot with nightversion to demonstrate: https://imgur.com/FGmHiwm

Confirmed in clean instance with only Bookshelf & Dark Utils

#### Versions
- Forge 1.14.4-28.1.103
- Bookshelf 4.4.71
- Dark Utilities 2.0.8

Original issue:
https://github.com/NillerMedDild/Enigmatica4/issues/195

**Comment by Darkhax** [comment]
Thanks for the issue report. This bug pops up every update because Mojang keeps changing the requirements lol. In this case some spawners worked fine, but natural spawning not so much.

**Comment by NielsPilgaard** [comment]
Porting must be so fun \o/

**Comment by adroslice** [comment]
[1.15.2 in FTB Omnia 1.1.0] Issue popped up again as the same, no natural spawning on vector plates.
