### ISSUE TITLE
export plate functions

### ISSUE THREAD

**Issue by cxcevents** [Darkhax-Minecraft/Dark-Utilities#197]
Export plate appears to accept a redstone signal to stop it from exporting. 

When a redstone signal is given to it, the plate turns black (assumably to show that it is off) but does not stop exporting.

not sure what the intended function exactly are. but the behavior im seeing is, when the plate is on, it takes items out of adjacent inventory and places them on top of the plate, and then moves the item entity away and onto the blockspace where its pointing. when given a redstone signal the plate turns black and DOES NOT stop exporting items on top of itself, but DOES stop moving the items into the space in front.

I would assume it should stop exporting as well as stop moving entities. 

![image](https://user-images.githubusercontent.com/14831458/73188811-6db38900-40f1-11ea-932b-97bf28f20f03.png)

**Comment by Darkhax** [comment]
Thanks for the issue report, this was a bug with all flat flat blocks that had ticking effects. The fix will be live on CurseForge soon. 

Related code: https://github.com/Darkhax-Minecraft/Dark-Utilities/commit/5e3a2ea5260f1f2323b484e136cd1011ad882589 https://github.com/Darkhax-Minecraft/Dark-Utilities/commit/129080ec4dbce85d0bec7f98cb49377c97704dbf
