### ISSUE TITLE
1.14.4 Game stops responding

### ISSUE THREAD

**Issue by Gamerbolts** [Darkhax-Minecraft/Dark-Utilities#198]
Hello. I am creating a modpack and have your mod in it. I was playing and testing and started getting on The One Probe "Waiting for Server". I checked my log and found this.

https://pastebin.com/9hgWwPbe

Not sure why it didn't crash and give me an official crash log.

Here is the full log [latest.log](https://github.com/Darkhax-Minecraft/Dark-Utilities/files/4233674/latest.log)

Thanks for the help!

**Comment by Darkhax** [comment]
Thanks for the issue report. This is a weird one, it looks like the game was trying to render a tooltip for an empty item, or perhaps an item that was not registered properly. The new version should skip over these error items now. Although some item you looked at is not acting as expected.

**Comment by Gamerbolts** [comment]
Interesting. I was looking at an Xnet block. 

Will try out the new version, thanks a bunch!
