### ISSUE TITLE
Game Crashes 1.15.2

### ISSUE THREAD

**Issue by TDeathlonger** [Darkhax-Minecraft/Dark-Utilities#201]
Loading up dark utilities and bookshelf together or separately with a fresh install of forge 1.15.2 will crash the game. Sorry, I have no idea if its because of this mod, bookshelf, both or something else. O.o [VVV Crash Report is below. VVV]
[crash-2020-03-26_14.14.06-client.txt](https://github.com/Darkhax-Minecraft/Dark-Utilities/files/4389982/crash-2020-03-26_14.14.06-client.txt)

**Comment by Darkhax** [comment]
Thanks for reporting this issue, you need to update your version of Minecraft Forge as Bookshelf now uses new features in Forge.
