### ISSUE TITLE
few errors in logs, didnt spotted any issue with mod yet

### ISSUE THREAD

**Issue by eloe79** [Darkhax-Minecraft/Dark-Utilities#202]
ok, is way to many of them, will just attached fill log and latest crash log to have list of everything that you can work on it, sorry for that if is too much
[latest.log](https://github.com/Darkhax-Minecraft/Dark-Utilities/files/4416778/latest.log)
[crash-2020-04-01_19.21.35-client.txt](https://github.com/Darkhax-Minecraft/Dark-Utilities/files/4416781/crash-2020-04-01_19.21.35-client.txt)

**Comment by Darkhax** [comment]
The crash you posted has nothing to do with my mods, seems to be a silent gems issue. The recipe errors in the latest.log are normal as those recipe systems have not been enabled for 1.15.2 yet.
