### ISSUE TITLE
wont boot up in 1.15.2

### ISSUE THREAD

**Issue by christomite** [Darkhax-Minecraft/Dark-Utilities#203]
i have many mods installed it may not be your mod causing the issue i cant figure it out though.
[crash-2020-04-06_11.21.17-client.txt](https://github.com/Darkhax-Minecraft/Dark-Utilities/files/4439614/crash-2020-04-06_11.21.17-client.txt)

**Comment by Darkhax** [comment]
Do you have the Bookshelf mod installed? It's a required dependency.

**Comment by christomite** [comment]
i just got it and a new crash showed up
[crash-2020-04-06_15.09.33-client.txt](https://github.com/Darkhax-Minecraft/Dark-Utilities/files/4440590/crash-2020-04-06_15.09.33-client.txt)

**Comment by Darkhax** [comment]
Trapcraft

**Comment by christomite** [comment]
i tried it  again and it worked this time i didnt change anything but thanks
