### ISSUE TITLE
[17Apr2020 16:41:37.005] [Server thread/ERROR] [net.minecraft.world.storage.loot.LootTableManager/]

### ISSUE THREAD

**Issue by BedrockLegends** [Darkhax-Minecraft/Dark-Utilities#204]
https://gist.github.com/BedrockLegends/3f089c797161ea6088aa9f2793ecd999

**Comment by Darkhax** [comment]
Thanks for reporting, this is a known issue as the slime crucibles have not been implemented on 1.15 yet.
