### ISSUE TITLE
1.15.2 game crash

### ISSUE THREAD

**Issue by zowdeep** [Darkhax-Minecraft/Dark-Utilities#206]
game crashes when I added this to my game 
[crash-2020-04-26_18.03.34-client.pdf](https://github.com/Darkhax-Minecraft/Dark-Utilities/files/4535996/crash-2020-04-26_18.03.34-client.pdf)

**Comment by Darkhax** [comment]
The mod requires Bookshelf which is marked as a dependency on the official download page.
