### ISSUE TITLE
Player Damage Trap crashed server

### ISSUE THREAD

**Issue by ClaudiusMinimus** [Darkhax-Minecraft/Dark-Utilities#207]
I had a player who placed some Player Damage Traps with a mob spawner and the server crashed.

Minecraft Version: 1.15.2
Java Version: 1.8.0_241
DarkUDarkUtilities-1.15.2-3.0.5

https://pastebin.com/MiPBwj7D

**Comment by Darkhax** [comment]
FTB Quests has a bug with fake players. This report goes to them.

**Comment by ClaudiusMinimus** [comment]
I forwarded to the dev. He will start working on FTB Quests later this month.
