### ISSUE TITLE
[1.14.4] Recipes involving dye are hardcoded to vanilla dyes instead of using forge:dyes

### ISSUE THREAD

**Issue by Sandriell** [Darkhax-Minecraft/Dark-Utilities#209]
Basically as the title says, recipes are using vanilla dyes like "minecraft:black_dye" versus using "forge:dyes/black".

Using: DarkUtilities-1.14.4-2.0.13

**Comment by Darkhax** [comment]
Thanks for pointing out this issue. Sorry it took so long for me to look at it.

**Comment by Darkhax** [comment]
Fixed in https://github.com/Darkhax-Minecraft/Dark-Utilities/commit/ceeded72a8bcd36ee1771521584ad7d70b738b5d a release for 1.14.4 will show up on curseforge soon.

**Comment by Darkhax** [comment]
The issue has also been fixed on 1.15.2.
