### ISSUE TITLE
Dark Utilities 1.15.2-3.0.5 client crashes on start

### ISSUE THREAD

**Issue by LuciusV** [Darkhax-Minecraft/Dark-Utilities#210]
Hi, it simply lets client crash.
Forge version: 31.1.88
Crash log:
[crash-2020-05-20_17.03.52-client.txt](https://github.com/Darkhax-Minecraft/Dark-Utilities/files/4655757/crash-2020-05-20_17.03.52-client.txt)
If mod is not present, game starts normally.

**Comment by Darkhax** [comment]
Do you have the Bookshelf mod installed? It's listed as a dependency on the mod page.

**Comment by LuciusV** [comment]
Yes I forgot it. Sorry :(
