### ISSUE TITLE
Crash when mobs are killed with player traps

### ISSUE THREAD

**Issue by benbenlaw** [Darkhax-Minecraft/Dark-Utilities#212]
a creeper dieing on a player casued a crash
[crash-2020-05-31_09.01.11-server.txt](https://github.com/Darkhax-Minecraft/Dark-Utilities/files/4707300/crash-2020-05-31_09.01.11-server.txt)

**Comment by Darkhax** [comment]
This is an issue with FTB Quests, they're not checking for fake players.
