### ISSUE TITLE
Vector Plates and Redstone Signal

### ISSUE THREAD

**Issue by papaworld** [Darkhax-Minecraft/Dark-Utilities#214]
Hi... great mod

In 1.12.2 the vector plates work perfectly for many design builds, even beyond mob control. But, in 1.15.2 redstone control to turn on/off the plates has been problematic for many uses vector plates can have. Is it possible to have the option to disable/enable the redstone control state on vector plates....  by individual plate GUI, or, a config file by each color of plate, or, preferably a new set of plates added that do not have redstone control. 

ThanX

**Comment by Darkhax** [comment]
This was fixed in #214, right clicking the plate with a redstone torch will lock it.
