### ISSUE TITLE
crucible doesn't appearing on item list

### ISSUE THREAD

**Issue by augustresende** [Darkhax-Minecraft/Dark-Utilities#215]
crucible doesn't appearing on item list on 1.15.2

**Comment by jmdev91** [comment]
Have you checked your config/darkutil.cfg file? It may be disabled there for some reason.
I'm having the same issue in 1.12.2, but there's no line in the config file for it in that version. Couldn't find any info on which version added it.

**Comment by Darkhax** [comment]
The item was added in 1.14.4 but hasn't been re-added to 1.15.2 yet.
