### ISSUE TITLE
[1.15.2] Portal charm sometimes gets stuck in loop

### ISSUE THREAD

**Issue by ocram9** [Darkhax-Minecraft/Dark-Utilities#217]
#### Description:
Sometimes when I use the portal charm I get stuck teleporting between portals (it eventually stops on its own though). I doesn't always happen so I can't give a way to 100% reproduce it, but I have fence gates in front of the portal in the overworld (though when I leave them open I can't move forward fast enough to not be teleported). Maybe a timeout after you have teleported would help?

#### Version:
- Minecraft 1.15.2
- Forge 31.2.20
- Dark Utilities 3.0.6

**Comment by Darkhax** [comment]
This issue is actually completely unrelated to the charm and can be reproduced without it. It may be a vanilla bug or something introduced by a commonly installed mod. I will consider adding cooldowns to some of the charm effects in the newer versions though.
