### ISSUE TITLE
Broken Chest Breaking Texture

### ISSUE THREAD

**Issue by InsomniaKitten** [Darkhax-Minecraft/Dark-Utilities#22]
Weird things happen when you break the decorative chests; they display the chest texture map instead of a block breaking overlay.

Bookshelf version: **[1.4.2.331](https://minecraft.curseforge.com/projects/bookshelf/files/2341156)**
Mod version: **[1.1.5.93](https://minecraft.curseforge.com/projects/dark-utilities/files/2341161)**
Forge version: **[12.18.2.2117](http://files.minecraftforge.net/maven/net/minecraftforge/forge/1.10.2-12.18.2.2117/forge-1.10.2-12.18.2.2117-changelog.txt)**

Examples:

![2016-11-02_14 27 07](https://cloud.githubusercontent.com/assets/9869940/19932659/cbd4c86e-a108-11e6-8e2f-3b0f0ae2e335.png)
![2016-11-02_14 27 22](https://cloud.githubusercontent.com/assets/9869940/19932660/cbddbce4-a108-11e6-9428-6724a28a0a96.png)
![2016-11-02_14 27 38](https://cloud.githubusercontent.com/assets/9869940/19932661/cbec0894-a108-11e6-98dd-8126cbf8ce1a.png)

**Comment by darkhax** [comment]
Very interesting, thank you for reporting. Will fix soon :)

**Comment by darkhax** [comment]
This is actually an issue with the Bookshelf code. I have opened a copy of this issue over there. I have already solved the issue, just want it on the right project so it can be tracked in the future.
