### ISSUE TITLE
[1.16.1] Gluttony Charm not working

### ISSUE THREAD

**Issue by Lassendc** [Darkhax-Minecraft/Dark-Utilities#222]
Description:
When trying to eat it make the fast eating sound but do not consume any food nor fill the hunger at all

Version:
Modpack: [All the Mods 6-0.24b](https://www.curseforge.com/minecraft/modpacks/all-the-mods-6/files/3024538)
Forge 32.0.106
Dark Utilities 1.16.1-4.0.2

**Comment by Lassendc** [comment]
I was also playing on a server if that is relevant

**Comment by medtryx** [comment]
I also ran into this issue running a custom modpack, I believe this was the same version of Forge and Dark Utilities though. It was a single player game.  I haven't had a chance to test it without other mods installed yet. 

*edit*

Recreated this with only: 

- Bookshelf-1.16.1-6.2.15.jar 
- forge-1.16.1-32.0.106-universal.jar 
- Runelic-1.16.1-1.0.6.jar 
- DarkUtilities-1.16.1-4.0.2.jar

**Comment by Darkhax** [comment]
Thanks for reporting and providing the info. This issue has now been fixed.
