### ISSUE TITLE
[Feature Request] Compatibility with Mekanism Canteen

### ISSUE THREAD

**Issue by medtryx** [Darkhax-Minecraft/Dark-Utilities#223]
Compatibility with Mekanism's Canteen of nutrient paste and the Gluttony Charm would be fantastic.

**Comment by Darkhax** [comment]
Took me ages but I finally got around to it. https://github.com/Darkhax-Minecraft/Dark-Utilities/commit/b6a4af39fb845a78a7db3d37f3981240df610f0f
