### ISSUE TITLE
1.16.1 Server Crash When Loading With Dark-Utils

### ISSUE THREAD

**Issue by stargateguy1** [Darkhax-Minecraft/Dark-Utilities#224]
Forge Version: 32.0.107
Mod Version: 4.0.3
MC Version: 1.16.1

I am getting a NoClassDefFound error when starting up the server. Client doesn't seem to have an issue. I have made sure all other mods are up to date as well.
PasteBin: https://pastebin.com/WwJ3JPMV

I'm probably doing something else wrong, so feel free to slap me! :)

**Comment by Darkhax** [comment]
You need to install Bookshelf, it's listed as a dependency on the Curse page.
