### ISSUE TITLE
[1.15.2] mob filters not inverting

### ISSUE THREAD

**Issue by Ruvanal** [Darkhax-Minecraft/Dark-Utilities#225]
I am trying to use child filters to sort cows.  While the child filter will work, I cannot get the inverted form to work.  Tried sneak right clicking with placed blocks and with the block in hand.  Neither method did any change.  JEI does not indicate any other way to create an inverted filter.  Also attempted to do the inverting with a player filter.

**Comment by Darkhax** [comment]
You need to sneak + right click with an empty hand to toggle the filter. Sneak clicking with something in your hand tells the game to bypass the block and try to place what is in your hand, like placing dirt onto the side of a chest without opening it.
