### ISSUE TITLE
Mobs aren't spawning on vector plates

### ISSUE THREAD

**Issue by FaveAsian** [Darkhax-Minecraft/Dark-Utilities#226]
I made a small mob farm with the whole floor covered in vector plates. However, no mobs are spawning. I made sure to be out of the 24 block range and I checked to make sure they could spawn.

**Comment by Darkhax** [comment]
Which version of the game and mod?

**Comment by FaveAsian** [comment]
Version 1.15.2
Modpack: FTB Omnia

**Comment by Darkhax** [comment]
Finally had time to test this out. Seems to be working fine with version 3.1.9 of Dark Utilities. 
[vector-plate-spawning-test-world.zip](https://github.com/Darkhax-Minecraft/Dark-Utilities/files/5579149/vector-plate-spawning-test-world.zip)
