### ISSUE TITLE
Server loading issues

### ISSUE THREAD

**Issue by nanonestor** [Darkhax-Minecraft/Dark-Utilities#227]
--See dark utils references in pastebin of console dump from dedicated server run startup sequence.  I'm seeing quite a lot of error messages thrown out. 

-Minecraft 1.15.2
Forge 31.2.36
-DarkUtilities-1.15.2-3.1.8.jar
-Bookshelf-1.15.2-5.6.40.jar

[https://pastebin.com/10sVfLi6](url)

**Comment by Darkhax** [comment]
Those are recipe errors for content that hasn't been added back into the game yet. They can be safely ignored.

**Comment by nanonestor** [comment]
Ok
