### ISSUE TITLE
[Suggestion] Glass Chest Content Rendering

### ISSUE THREAD

**Issue by InsomniaKitten** [Darkhax-Minecraft/Dark-Utilities#23]
It'd be cool if there was a toggleable feature that rendered the first few inventory items of the Glass Chest in it's model, much like the Crystal Chest from [Iron Chests](https://minecraft.curseforge.com/projects/iron-chests).

**Comment by darkhax** [comment]
This is a good suggestion, however it increases the amount of time it takes for those chests to render. I will keep this in mind and may re-open at another time.
