### ISSUE TITLE
No configs 1.15

### ISSUE THREAD

**Issue by CrazyLewis** [Darkhax-Minecraft/Dark-Utilities#234]
Hello

If this is the same as #213 please close it.

I have moved from 1.12.2 to 1.15.2 and now do not see a config file i can edit as in 1.12 i had changed how far ender hoppers reach so if you could let me know if the file has been moved/name changed or no config file as of yet in the version i am using please.

DarkUtilities-1.15.2-3.1.8 ( Current one i am using )

**Comment by Darkhax** [comment]
The config file was removed in 1.13+ due to all the changes Forge made. It will be re-added again eventually but only for 1.16 as it's a lot of work to add.
