### ISSUE TITLE
More a Question as an Issue

### ISSUE THREAD

**Issue by DarkBreaker09** [Darkhax-Minecraft/Dark-Utilities#237]
Hey i am using the Version 1.16.3-6.0.3

Is there any Config file where i need to enable the Tether and
can change some settings to the Traps ?

I cant find any Config file.

**Comment by Darkhax** [comment]
Hello, the Ender Tether is not currently a part of DU on 1.16. There is also no config file for the mod, although there may be one in the future.

**Comment by Avi-E-Koenig** [comment]
Will the tether be added again in the future?

**Comment by Darkhax** [comment]
@Darkmift Eventually. No ETA.
