### ISSUE TITLE
Ender hopper

### ISSUE THREAD

**Issue by Archuhi3** [Darkhax-Minecraft/Dark-Utilities#238]
Hello first time on here...

I'm playing "All the Mods 6" and I cant seem to make ender hoppers. 
All I can find in JEI is a description of what it does and no recipe. 
All the recipes I've seen online don't craft it either. 

A little halp please?

**Comment by Darkhax** [comment]
The ATM6 team removed the recipe. They think it's laggy for some reason and don't want you to use it. https://github.com/AllTheMods/ATM-6/blob/bcc83aaafbd42db00a4e7de0bb695e3fa55c0936/kubejs/server_scripts/banned_items.js#L11

**Comment by Archuhi3** [comment]
dang alright. thanks for the quick reply!
