### ISSUE TITLE
Slime Crucible isn't available

### ISSUE THREAD

**Issue by Jkjr1** [Darkhax-Minecraft/Dark-Utilities#244]
Hi :) 
The "Slime Crucible" does not exist in the mod - or i cant see / craft it?

Maby it is a bug? i have installed "bookshelf" as well as "runelic" and all mods ar updatet to the newest version :) 

![Skærmbillede 2021-02-08 185744](https://user-images.githubusercontent.com/78753953/107261423-95953680-6a3f-11eb-811f-66911993cc3f.jpg)

**Comment by Darkhax** [comment]
The Slime Crucible is no longer in the mod. I would like to re-add it in a future version but there is no ETA.
