### ISSUE TITLE
Fast Export/Import Plates should be craftable using Fast Vector Plates

### ISSUE THREAD

**Issue by aaronhowser1** [Darkhax-Minecraft/Dark-Utilities#246]
Right now you can only craft them using normal Export/Import Plates, so if you have a bunch of Fast Vector Plates you can't use them.

This should also apply to Extreme Plates.

**Comment by Darkhax** [comment]
I like the spirit of this request but I think this would have unintended consequences. For example the standard vector plates use 0.33 iron/gold nuggets per plate, and the export/import plates use 1 iron/gold nuggets per plate. This isn't a huge deal but it would open up an iron/gold dupe with uncrafting mods. Feel free to add this using CraftTweaker or something though.
