### ISSUE TITLE
[Feature Request] Cursed Earth

### ISSUE THREAD

**Issue by florian-berger** [Darkhax-Minecraft/Dark-Utilities#248]
Since there is no mod for current minecraft versions that adds Cursed Earth, I would be glad to see this kind of blocks in this mod.

For now, I am already using the damage traps for my mob farm, but without boosted spawns, I can't get enough drops.

**Comment by Darkhax** [comment]
Hello,

I am not really interested in taking features that other mods are known for. I may have some similar/overlapping features but I try to give everything a unique/original spin. In this case my mod already has the spawning monolith, but that is not in current versions and I am not actively working on that system right now.
