### ISSUE TITLE
If a player gets on an Anchor Plate, it should display in chat that they can get off by sneaking

### ISSUE THREAD

**Issue by aaronhowser1** [Darkhax-Minecraft/Dark-Utilities#251]
If someone has one in their base and another person gets trapped in one, they will have no idea what the heck is going on. Telling them what's happening and how to leave would fix that.

**Comment by Darkhax** [comment]
Makes sense, will slip this in the next update. 
![unknown](https://user-images.githubusercontent.com/2250798/111897722-31bf3f80-89e7-11eb-99fa-38feaf22d2fc.png)
