### ISSUE TITLE
[Suggestion] A way for export plates to extract from the bottom face of a block

### ISSUE THREAD

**Issue by CplPibald** [Darkhax-Minecraft/Dark-Utilities#253]
Suggestion: Allow export plates (or some new plate) to extract from the bottom of a block, and not just the sides.

I've always liked conveyor belts over pipes for that MC "factory" look, and was really happy to see the export/import vector plates in Dark Util.  I tried to build some factory automation using all vector plates, and I realized there's no way to automate a vanilla furnace (or any other machine that outputs from the bottom), because they can only extract the fuel; not the output.

**Comment by Darkhax** [comment]
This was an intended limitation of the export plates, they were not really intended for these use cases. There is definitely room for a new block that can transform vertical connections to horizontal ones though, this may be added to the next content update.
