### ISSUE TITLE
Memory leak in latest release 1.16.5-8.0.9 version

### ISSUE THREAD

**Issue by starmun-0010** [Darkhax-Minecraft/Dark-Utilities#256]
**Mod Version:**   DarkUtilities-1.16.5-8.0.9.jar
**Forge Version:** 36.1.4
**MC Version:**    1.16.5

### Description
Any chunk which has entities does not unload when player leaves the loaded radius area. Resulting in a memory leak and eventual tps death.
The issue seems to only exist with the latest release version and disappears with DarkUtilities-1.16.5-8.0.6.jar

### To Reproduce
- Install Crash Utilities
- Install Dark Utilities
- Run the game
- Travel in any direction
- Monitor the loaded chunks in crash utilities
- The chunks beyond the chunk load radius will never unload.

### Expected behavior
When player moves beyond the chunk load radius, the chunks outside the radius should unload.

### Screenshots:
![image](https://user-images.githubusercontent.com/5557278/115311720-8e9a4b00-a189-11eb-8ff6-99007e1ec4a2.png)
![image](https://user-images.githubusercontent.com/5557278/115311731-93f79580-a189-11eb-9b6f-8256be580936.png)

### Screenshot of correct behavior (previous alpha version of Dark Utils)
![image](https://user-images.githubusercontent.com/5557278/115312647-20568800-a18b-11eb-9ff1-ea74348e3666.png)

**Comment by Darkhax** [comment]
Thanks for the report, could you verify that this bug has been fixed in [8.0.10](https://www.curseforge.com/minecraft/mc-mods/dark-utilities/files/3283227)?

**Comment by starmun-0010** [comment]
Issue is fixed, no longer is there a trail of unloaded chunks and entities. Thank you
![image](https://user-images.githubusercontent.com/5557278/115466967-3d9e5b80-a24a-11eb-9c9e-5b6cef2ab827.png)
