### ISSUE TITLE
Server TPS destruction (1.12.2)

### ISSUE THREAD

**Issue by ObsidianFlight** [Darkhax-Minecraft/Dark-Utilities#257]
Tried breaking a player trap my brother placed in our house, got spammed with 
[22:23:41] [Server thread/WARN]: Attempted to get a UUID for player FAKE_PLAYER_DARK_UTILS, but that account is not registered
in the latest.log

this is in 1.12.2 so im unsure if you still support that version but its an issue i see no response to on google so id like to know if anyone has info on what could be causing this

Modlist: https://justpaste.it/7ee1h

**Comment by ObsidianFlight** [comment]
after doing some testing, I found out that standing on a player trap causes tps to die, i ended up stepping on 2 of them at once and happened to stand on them for too long, and break them too late,

now the issue is why would they cause so much lag for a player to stand on one?

**Comment by Darkhax** [comment]
1.12.2 is not being supported anymore. The log entry `Attempted to get a UUID for player XYZ, but that account is not registered` does not seem to be from Forge or the Vanilla game, meaning another mod is posting that error. I am guessing their mod does something when one player damages another (like maybe a chunk claiming mod) and does not account for fake players.
