### ISSUE TITLE
Can't get Wither Dust :(

### ISSUE THREAD

**Issue by Immaculala** [Darkhax-Minecraft/Dark-Utilities#259]
I have DarkUtilities-1.16.5-8.0.10
and as per instructions “This mod requires the Bookshelf library! On 1.16+ you will also need the Runelic mod”
Bookshelf-1.16.5-10.2.15
Runelic-1.16.5-7.0.1

but cannot get Wither Dust - what am I missing?
Is this an issue or am I just being dim?
![2021-08-03_23 24 55](https://user-images.githubusercontent.com/26187212/128094352-86aba774-93bd-4125-b872-1394eabfec90.png)

**Comment by Darkhax** [comment]
Wither dust was removed from the mod in 1.13. None of the crafting recipes or features use it anymore, if they do it's probably something added by another mod or modpack.

**Comment by Immaculala** [comment]
Ahhhhh, thank you for the fast response; I thought I was doing something dumb.
