### ISSUE TITLE
Conflict with Chisel

### ISSUE THREAD

**Issue by charlesbevans** [Darkhax-Minecraft/Dark-Utilities#26]
The stone ore dict option interferes with Chiseling diorite, andesite, etc. (https://github.com/Chisel-Team/Chisel/issues/280#issuecomment-264121599)
What does turning that off do to the mod?

**Comment by darkhax** [comment]
Disabling this option will limit any crafting recipe which uses Stone to just smooth stone, and not any of the other stone variants.

**Comment by charlesbevans** [comment]
I can get around that with a script if I need to. Thanks.
