### ISSUE TITLE
[Suggestion] Make entity specific filter

### ISSUE THREAD

**Issue by niklas2233** [Darkhax-Minecraft/Dark-Utilities#260]
Hey could you add specific filter for entities or if you could make it so the name mob filter to name the entity you want to filter if. dont know if thats possible or if you just dont want to flood the game with items but it would be cool if you could make it so filter specific entity :)

**Comment by Darkhax** [comment]
Thanks for the feedback. I get why you would want this feature but I generally don't like adding things that target very specific use cases. It's often better game design to give players tools they can use to build stuff themselves. For example you can combine multiple filters together in a contraption to narrow down the type of mob. Inverted filters are especially useful in this context.

If someone else wants to make an addon or make their own mod with this type of feature I would have no issues with that.
