### ISSUE TITLE
Can't enter twilight forest portal while having Portal Charm

### ISSUE THREAD

**Issue by nin8995** [Darkhax-Minecraft/Dark-Utilities#261]
Portal Charm doesn't work when you enter twilight forest portal, but you can't warp to the Twilight Forest.

**Comment by InsideBSITheSecond** [comment]
I don't have this issue in my custom 1.12 pack

Forge 14.23.5.2855
DU 1.8.230
TF 3.11.1021

**Comment by LeSwede** [comment]
I have this issue too.

Forge: 36.2.4
MC: 1.16.5
Dark Utilities: 8.0.10
Twilight: 4.0.546

**Comment by Darkhax** [comment]
This issue stems from the Twilight Forest portal handling the portal timer in a way that is inverted to vanilla. I've created a copy of this issue on their issue tracker with more details. Not sure what the best route to fix this issue will be yet. https://github.com/TeamTwilight/twilightforest/issues/1441

**Comment by Darkhax** [comment]
It looks like the Twilight Forest team has fixed this on their end. https://github.com/TeamTwilight/twilightforest/commit/390bc8e42d19dc705fad253a205052321ec21dc9
