### ISSUE TITLE
Bug report about Player Filters

### ISSUE THREAD

**Issue by ZygZagGaming** [Darkhax-Minecraft/Dark-Utilities#262]
The bottom north-west corner of a Player Filter has a collidable hitbox for players

**Comment by ZygZagGaming** [comment]
Sorry, accidentally hit enter while typing the issue.

**Comment by Darkhax** [comment]
I am not able to reproduce this issue, and looking at the code the filter has the exact same hitbox as air, torches, and other blocks without hitboxes. Is it possible that another mod in your game instance is causing this issue, or perhaps you have something like chisel and bits below the block, or you're wearing something that changes the player hitbox size?
