### ISSUE TITLE
Dark-Utilities Not loading properly on launch.

### ISSUE THREAD

**Issue by Cube420** [Darkhax-Minecraft/Dark-Utilities#264]
I am playing my own mod pack and I wanted to add this mod but it doesn't load properly on launch this makes me and my friend very sad :( and if anyone know how to fix this please let me know

**Comment by Darkhax** [comment]
Hello, have you installed all of the dependencies like Bookshelf?

If you still can't get it to work please upload your latest log file and I can tell you specifically why it's not working.

**Comment by Alec153** [comment]
I was having the same issue until I added bookshelf. You should probably add bookshelf as a dependency in your fabricmod.json.

**Comment by Darkhax** [comment]
The bookshelf dependency is now explicitly defined for fabric.
