### ISSUE TITLE
[Suggestion] Make sneaky levers have state-independent textures

### ISSUE THREAD

**Issue by osirisgothra** [Darkhax-Minecraft/Dark-Utilities#271]
The simplest way would probably be keep the same behavior, but when a texture is applied while the lever is on, that is the texture for the 'on' state, and if applied while it is off, the texture would be for the 'off' state obviously. To keep compatibility with the original behavior, the first texture applied could be for both states until another one is applied after that. 

So basically the procedure would be either
(for one texture on a lever)
place the block, apply the texture

(for state-specific textures)
place the block, set to the desired texture, then turn on to set a specific 'on' texture (obviously the other one will be the 'off' texture)

If either are removed, it reverts back to the old behavior of having one texture, simple enough right?
Since the levers aren't updated by anything but players afaik, shouldn't be a performance issue.
Servers that don't like this idea could just shut the behavior off as a config setting, if it was really needed.

oh....man
i think thats it
yeah

**Comment by Darkhax** [comment]
Hello, thanks for the suggest. This seems a bit niche but I like the idea over all. Unfortunately the older versions of this mod are not being updated with new features, and newer versions of this mod do not have sneaky blocks anymore. Some game engine stuff changed under the hood and I haven't found a decent way to update the sneaky blocks to modern versions of the game yet.
