### ISSUE TITLE
Drowned not Filtered by Water Mobs Filter Block

### ISSUE THREAD

**Issue by Nonsanity** [Darkhax-Minecraft/Dark-Utilities#274]
Running version 10.0.4

The water mobs filter block doesn't allow Drowned to pass through. They probably should count as "water" mob.

I was trying to make a zombie drowning farm where a zombie spawner makes normal zombies that are pushed into a water chamber to drown. I tried to use the water mobs filter to prevent them from entering the kill chamber until after they had converted, but they still couldn't pass.

**Comment by Darkhax** [comment]
Thanks for the suggestion. I've updated the 1.18.2 and 1.19 versions of the mod to include the Drowned in this filter's rule. You can now update to 10.0.5.

- [10.0.5 for Forge 1.18.2](https://www.curseforge.com/minecraft/mc-mods/dark-utilities/files/3830309)
- [10.0.5 for Fabric 1.18.2](https://www.curseforge.com/minecraft/mc-mods/dark-utilities/files/3830308)
- [11.0.2 for Forge 1.19](https://www.curseforge.com/minecraft/mc-mods/dark-utilities/files/3830305)
- [11.0.2 for Fabric 1.19](https://www.curseforge.com/minecraft/mc-mods/dark-utilities/files/3830304)
