### ISSUE TITLE
[Suggestion] Mob Filter (Adult)

### ISSUE THREAD

**Issue by Eydamos** [Darkhax-Minecraft/Dark-Utilities#276]
I would like to have a mob filter for adult mobs.

Use case:
Use a Mob Filter (Child) to filter out children. Then they wait there until they are grown up and can then be separated by a Mob Filter (Adult) to a killing chamber as children do not drop anything.

Proposal recipe: Just put a Mob Filter (Child) in the crafting grid to transform it into the Adult version and a Mob Filter (Adult) in a crafting grid switches it back to the Child version.

**Comment by Darkhax** [comment]
You can invert a mob filter by sneak clicking on it. This will make it filter out the anything that doesn't match the original condition.
