### ISSUE TITLE
(1.18.2) StartUp Dependency Error Messages missing !

### ISSUE THREAD

**Issue by Speecker** [Darkhax-Minecraft/Dark-Utilities#277]
DarkUtilities-Forge-1.18.2-10.0.5 does not tell you its dependencies on startup and just crashes MC. should be changed i guess ;)

**Comment by Darkhax** [comment]
The dependencies are [defined as Forge intends](https://github.com/Darkhax-Minecraft/Dark-Utilities/blob/1.18.2/Forge/src/main/resources/META-INF/mods.toml#L33-L38), however Forge can be very hit or miss on actually displaying that to users. Starting in 1.13+ they will continue trying to load the game with missing dependencies and only show the error screen if the game can load to the main menu without the missing dependencies.
