### ISSUE TITLE
Crash on startup fabric

### ISSUE THREAD

**Issue by IskallDoe** [Darkhax-Minecraft/Dark-Utilities#278]
Minecraft version: 1.18.2
Fabric version: 0.14.8
Fabric api version: fabric-api-0.57.0+1.18.2.jar
Mod version: DarkUtilities-Fabric-1.18.2-10.0.5.jar
Lib version: PigPen-Fabric-1.18.2-8.0.1.jar

Message error: 
The game crashed whilst initializing game
Error: java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'darkutils'!

Problem:
The game crashes at the startup.

Crash report: https://pastebin.pl/view/050a247b

**Comment by Darkhax** [comment]
I believe the actual issue here is with the materialisation mod. Looks like they are missing a mixin refmap.

> Caused by: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: Critical injection failure: @Inject annotation on renderGuiItemOverlay could not find any targets matching 'renderGuiItemOverlay(Lnet/minecraft/client/font/TextRenderer;Lnet/minecraft/item/ItemStack;IILjava/lang/String;)V' in net.minecraft.class_918. No refMap loaded. [PREINJECT Applicator Phase -> materialisation.nooptifine.mixins.json:MixinItemRenderer from mod (unknown) -> Prepare Injections ->  -> handler$gco002$renderGuiItemOverlay(Lnet/minecraft/class_327;Lnet/minecraft/class_1799;IILjava/lang/String;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V -> Parse]

**Comment by IskallDoe** [comment]
Oh, I didn't remember to have installed that mod. Sorry if I have bothered
you when your mod was not the problem. I still haven't learned how to read
crashes reports properly. Thank you for your fast response and I wish you a
nice rest of the day!

Il lun 18 lug 2022, 20:55 Tyler Hancock ***@***.***> ha
scritto:
