### ISSUE TITLE
Forge sever problem 1.18.2

### ISSUE THREAD

**Issue by ErLewih** [Darkhax-Minecraft/Dark-Utilities#281]
Im trying to play in a serer w/ friends and the last mod that i need is this, but when i try to enter, it says i need version 10.0.5 of this mod, wich i have already installed, anyone can help me?
I dont understand the problem i have the right version but it doesnt work, the server is forge, i tried even donlawing fabric version and also doesnt work. Thanks for your help and your time :D

**Comment by Darkhax** [comment]
Please include the log files.

**Comment by Proxwian** [comment]
Have the same issue, why did you closed it?

**Comment by Darkhax** [comment]
@Proxwian It was closed by accident.

**Comment by Proxwian** [comment]
Solved on my side. Just need to see logs and verify if it was by other mod using integrations

**Comment by Proxwian** [comment]
In my case it was mod runelic, accidently deleted on client side and not deleted on my server

**Comment by Darkhax** [comment]
I am going to assume the original poster has figured out the issue on their own or they are no longer interested in using the mod. If this is not the case please create a new issue.
