### ISSUE TITLE
[Suggestion] Mob Filter (Adult)

### ISSUE THREAD

**Issue by ApolloHusky** [Darkhax-Minecraft/Dark-Utilities#287]
I really like the mob filters and I noticed there's a filter for baby animals. I have an idea for a chicken farm but I want the baby chickens to sit and grow up before being put into a cooking machine. A mob filter that only allows adult animals to pass through would be the perfect thing for it but it doesn't seem to exist rn.

**Comment by Darkhax** [comment]
Hello, if you sneak and right click the mob filter the frame will turn white and it will be an inverted filter. This will make the filter allow everything except for that type of mob through it. So an inverted baby filter will only let non-baby mobs fall through. Hope this helps.
