### ISSUE TITLE
Hostile mob filter allows incorrect mobs to pass through. 

### ISSUE THREAD

**Issue by TheDarkFlame** [Darkhax-Minecraft/Dark-Utilities#288]
https://nekoyue.github.io/ForgeJavaDocs-NG/javadoc/1.18.2/net/minecraft/world/entity/MobCategory.html

I've been playing with minecolonies mod and noticed that citizens there follow rules for hostile filters as if they are hostile. This is because they are created as a [MobCategory.CREATURE](https://github.com/ldtteam/minecolonies/blob/cebc69c7281f19f1112d1f76d4d20b8fe8143e19/src/main/java/com/minecolonies/apiimp/initializer/EntityInitializer.java#L45)
I see that you are filtering based on [Mob and ~MobCategory~MobType](https://github.com/Darkhax-Minecraft/Dark-Utilities/blob/f3f5869d423835ac563b8a1152a1f64671072e34/Common/src/main/java/net/darkhax/darkutilities/features/filters/Filters.java). It might be helpful to add in extra filters based on the [MobCategory](https://nekoyue.github.io/ForgeJavaDocs-NG/javadoc/1.18.2/net/minecraft/world/entity/MobCategory.html) entity, specifically, CREATURE and MONSTER.

**Comment by Darkhax** [comment]
Hello, the hostile filter does not appear to check mob categories at all? Originally this code checked for the [MonsterEntity](https://github.com/Darkhax-Minecraft/Dark-Utilities/blob/1.16.5/src/main/java/net/darkhax/darkutils/features/filters/Filters.java#L50) interface level class marker. In the 1.18.2 port we moved over to Mojang's official class mappings and it looks like this code was [incorrectly updated to check for Mob](
https://github.com/Darkhax-Minecraft/Dark-Utilities/blob/1.18.2/Common/src/main/java/net/darkhax/darkutilities/features/filters/Filters.java#L32) when it should be checking for the Enemy marker interface. This should mean that the filter has a bug that would allow most mobs through such as horses and fish as well?

**Comment by TheDarkFlame** [comment]
Apologies, meant that your filter is using Mob and MobType (not MobCategory).

I'm not running the latest build, but this bug exists in the version I am running (13.1.6), and source code suggests no changes since then.


In testing to confirm, I was able to push a sheep through the filter.


Also might be nice to add a custom entity selection, although that may require a bit more work...

**Comment by Darkhax** [comment]
Thanks for letting me know. This has been corrected for 1.18.2 and 1.19.2 on both Forge and Fabric.
