### ISSUE TITLE
Modrinth builds

### ISSUE THREAD

**Issue by tranquillity-codes** [Darkhax-Minecraft/Dark-Utilities#290]
[Modrinth](https://modrinth.com/) is a community driven open source platform for hosting mods. Unlike curseforge, it has a proper public API, does not use cloudflare, has a better search implementation, and many other benefits.

Uploading to Modrinth would undermine the monopoly of curseforge, helping the modding community to grow, rather than being held back by the whims of a corporation.

I am not sure if you have already received requests or have already considered Modrinth, if that is the case I apologize.

If you do not have time to maintain builds on another platform, with your permission I could build & upload.

**Comment by Darkhax** [comment]
Hello, I have considered uploading my mods to Modrinth but I am not interested in doing that at this time. I am also asking that 3rd parties do not rehost my mods to Modrinth except for the case of modpack overrides that are done in line with the license.
