### ISSUE TITLE
DarkUtilities doesn`t load correctly when launching

### ISSUE THREAD

**Issue by RobTuber** [Darkhax-Minecraft/Dark-Utilities#293]
Hey I just installed the modpack and put it in my mods folder together with bookshelf, runelic and pig pen cipher. Now when I launch my game it tells me that DarkUtilities has failed to load correctly. java.lang.reflect.InvocationTargetException: null is what it says. Can someone pls help me. I`d really like to play the modpack

**Comment by Darkhax** [comment]
Hello,

You haven't included the version numbers or your log file. These are very important for helping others track down any issues that would prevent the game from launching. Based on the limited information you provided I am guessing you forgot to install Bookshelf which is a listed dependency of the mod.
