### ISSUE TITLE
Dark Utilities doesn`t load correctly

### ISSUE THREAD

**Issue by RobTuber** [Darkhax-Minecraft/Dark-Utilities#295]
Okay let´s try this again.
In my mods folder I have Bookshelf-Forge-1.19.3-17.0.5 / DarkUtilities-Forge-1.19.2-17.1.7 / PigPen-Forge-1.19.2-11.1.2 / Runelic-Forge-1.19.3-15.0.1 and TravelersBackpack-1.19.3-8.3.4. I have 1.19.3-forge-44.1.23 installed.
Now when I launch minecraft it tells me that DarkUtilities has failed to load correctly (java.lang.reflect.InvocationTargetException: null)
I´d really like to play DarkUtilities and would appreciate a way to fix it. Please keep in mind that I´m not good with mods and need a step by step fix.

This is my latest log right after it crashed.
[latest.log](https://github.com/Darkhax-Minecraft/Dark-Utilities/files/10967037/latest.log)

**Comment by Darkhax** [comment]
Oh, you're trying to use a 1.19.2 version on 1.19.3. Generally mods can only be used with the version they were released for so you can't do that. This is because Mojang changes a lot of code each update. The fix is to wait for an official 1.19.3 release of Dark Utilities.

**Comment by RobTuber** [comment]
So I didn't screw it up. It's just not compatible. Okay I'll try it with 1.19.2. Thanks for the help
