### ISSUE TITLE
mob filter (player)

### ISSUE THREAD

**Issue by iiJonno** [Darkhax-Minecraft/Dark-Utilities#299]
![image](https://github.com/Darkhax-Minecraft/Dark-Utilities/assets/127353505/81ee1d99-2a68-43ec-af3d-8f093c8fc3a6)
 not sure if this is your issue or not but i cant craft mob filter (player)

**Comment by Darkhax** [comment]
Which version?

**Comment by iiJonno** [comment]
ah sorry  1.20-16.0.1
with bookshelf 1.20-19.0.15

**Comment by Darkhax** [comment]
Thanks for letting me know about this. Version 16.0.3 should now be live on CurseForge which fixes this.

**Comment by iiJonno** [comment]
cool thanks for the quick update
