### ISSUE TITLE
cannot craft anything from dark utilities

### ISSUE THREAD

**Issue by jdratlif** [Darkhax-Minecraft/Dark-Utilities#30]
Trying to craft vector plates, but when I try to do so, the crafting seems to work (i.e. I start to take it out of the crafting table), but the item doesn't materialize (it disappears after I take it). JEI has "tooltip error, see log" on every dark utilities item. I can't even JEI cheat them in. Not sure what "log" it's referring to, but I didn't see anything useful on the server or client side. If there's something I can send you to help diagnose, please let me know.

In the crafting table, the item being crafted is tooltip'd as "Unnamed 0", but the icon is the green vector plate.

Minecraft 1.10.2
Forge 2185
Dark Utilities 1.1.6.99

**Comment by darkhax** [comment]
Are you playing on a server? If so, you need to have that mod on a server as well.

**Comment by jdratlif** [comment]
I was sure I did that when I added the mod to my pack, but apparently I did not. Sorry for wasting your time. Thanks.
