### ISSUE TITLE
[bug] Warding Charm

### ISSUE THREAD

**Issue by RamenNoodles** [Darkhax-Minecraft/Dark-Utilities#300]
The description states "Wards off negative status effects"

I assume by _negative effects_ it refers to poison, wither, mining fatigue maybe darkness but I still get affected by those negative effects.

**Comment by Darkhax** [comment]
Yes, you will still be affected by those effects however the duration will be reduced by 50%. So if you have a negative effect for 60 seconds it will actually expire in 30.
