### ISSUE TITLE
[FEEDBACK] Will there be an update for 1.21?

### ISSUE THREAD

**Issue by Nova-Katt** [Darkhax-Minecraft/Dark-Utilities#306]
### Minecraft Version

1.20.4

### Mod Loader

Fabric

### Feedback

Hello there! :)
Just wanted to know if there are any plans to update this mod for 1.21 aswell? I'm currently running it on 1.20.4 with my gf and we are having SO much fun with it, and we are planning to eventually update our server to 1.21 when all (or most) of our essential/most wanted mods have been updated to 1.21, aaaaand we would LOVE if this one was ported to 1.21 aswell.
So, are there any plans for that?
Just wanted to know. :)
Cheers!

**Comment by Darkhax** [comment]
Hello, yes I will be updating this mod to 1.21. Mojang changed a lot this time so it's taking me a bit longer than usual, but it will happen eventually.

**Comment by Nova-Katt** [comment]
How is the progress on this? And now with the micro updates and mods spread out between 21, 21.1, 21.2, 21.3 and 21.4.... is it going to be available for just one of those, or will it be 21.x?
I currently have two games, we are at 1.21 at my gf's place, and 1.21.1 at my place (most mods we use are on those versions).
So just looking for an update when on the horizon this could be available? and if it will be for 1.21/1.21.1 or only for 1.21.4 (which has very few mods as of today)
Cheers!

**Comment by Darkhax** [comment]
Hello, 

I finished porting all of the dependencies for this mod and have slowly been making my way through porting this one. My current plan is to finish up the BotanyPots port, and some of my smaller mods in the next few days, and then things will pick up with this mod. 

Unfortunately while these updates may seem small to players, Mojang has been making a lot of changes to the underlying game engine. To give you an idea, their internal data version was 18 for 1.20.4, and 1.21.4 is version 61. 

I am targeting 1.21.1 for now. I am planning to skip .2 and .3. I would like to support .4 in the future but who knows what version we will be at when I am done with .1 lol

**Comment by Nova-Katt** [comment]
Yeah I heard the jump from 1.20 to 1.21 included a massive rewrite of the structure which made it trickier to rewrite them. I'm impressed at the ones who done it so fast. 🙏

And then they made it even trickier with not doing big updates but only doing multiple minor ones. It's such an annoyance for devs who spread out their mods all over the versions now.
But it seems like some versions are more popular at least.
1.20.1
1.20.4
1.21.1
So I'm happy to see you're doing the 21.1, that's the one I run my own game at home with. 🗡️ Looking forward to when you're done with it.
