### ISSUE TITLE
[BUG] Child filter not letting baby zombies pass.

### ISSUE THREAD

**Issue by AnonTheMouse** [Darkhax-Minecraft/Dark-Utilities#307]
### Minecraft Version

1.20.1

### Mod Version

1.20.1-17.0.3.jar

### Mod Loader

Forge

### What environment are you running the mod in?

Client

### Issue Description

I'm playing on a friend's server based on one of the Valhelsia packs, and have a mob farm that requires a gap big enough for baby zombies to pass through (due to use of other modded components). So I set up a pit with Child filters to drop the baby zombies into before they can reach my kill spot, but they have no issues standing on the filter blocks and getting to me.

**Comment by Darkhax** [comment]
Thank you for letting me know about this issue. I've pushed the [17.0.5](https://www.curseforge.com/minecraft/mc-mods/dark-utilities/files/5754567) update which should fix this.
