### ISSUE TITLE
Sneaky Lever blocks always emit signal

### ISSUE THREAD

**Issue by AstroxV** [Darkhax-Minecraft/Dark-Utilities#31]
Not sure if it is something for EnderIO or here, but I'll post it here anyway.
When connecting a redstone conduit to a hidden sneaky lever, it will always submit a redstone signal whatever state the lever is in. It works fine with vanilla  redstone.

**Comment by darkhax** [comment]
Sounds like an issue with the redstone conduit, so I would ask the enderio devs. If it turns out to be an issue on my end I will look into fixing it though.

**Comment by PapiDimmi** [comment]
This is not a bug in Ender IO.
