### ISSUE TITLE
Sneaky Blocks should override Block.shouldSideBeRendered

### ISSUE THREAD

**Issue by bs2609** [Darkhax-Minecraft/Dark-Utilities#33]
Currently, placing transparent/translucent looking blocks next to each other shows 'inside' faces, unlike the blocks themselves.

**Comment by darkhax** [comment]
While I am going to add this, it won't actually help as much as expected. For example, the code in BlockGlass for this method specifically checks if the block is a glass block or a stained glass block. A custom check would be required for every block which uses this state. I will take care of the vanilla edge cases myself, however if other mods do these checks, that will be on them.

**Comment by darkhax** [comment]
This was closed in https://github.com/Darkhax-Minecraft/Dark-Utilities/commit/17ae794d290bda7f0f8e6caf5c813a37dd36e90b
