### ISSUE TITLE
Redstone timer doesn't respond to redstone signal to disable it.

### ISSUE THREAD

**Issue by jeridan** [Darkhax-Minecraft/Dark-Utilities#34]
Pack: Direwolf20 1.0-1.0.2-1.3.2
Dark Utilities: DarkUtilities-1.10.2-1.1.6.103

I cannot get the timer to stop even with a lever turned on next to it.

![2017-01-11_22 13 03](https://cloud.githubusercontent.com/assets/5779504/21876710/2f33a83e-d84b-11e6-8547-412e7843d197.png)
![2017-01-11_22 13 06](https://cloud.githubusercontent.com/assets/5779504/21876713/31b92bba-d84b-11e6-9106-34ba7383d97b.png)

**Comment by darkhax** [comment]
I've not been able to reproduce this issue. Best suggestion I have would be to try directly powering it with a repeater.
