### ISSUE TITLE
Recent server crash looks to be from DarkUtilities FeatureAntiSlime

### ISSUE THREAD

**Issue by krishaman** [Darkhax-Minecraft/Dark-Utilities#35]
Recent server crash looks to be from DarkUtilities FeatureAntiSlime.

MineCraft 1.10.2
Forge 12.18.3.2185
darkutils 1.1.6.103

Attached crash log.

...

[crash-2017-01-12_18.24.01-server.txt](https://github.com/Darkhax-Minecraft/Dark-Utilities/files/703526/crash-2017-01-12_18.24.01-server.txt)

**Comment by darkhax** [comment]
Thank you for reporting this. The issue is very hard to reproduce, however I have seen it in the past. It has to do with the way Mojang changed how the world is loaded. I will try to fix this, but until then you shouldn't have too many issues with this.

**Comment by aaronmallen** [comment]
https://github.com/SlimeKnights/TinkersConstruct/issues/2719
