### ISSUE TITLE
Lol Tnt

### ISSUE THREAD

**Issue by DinnerBeef** [Darkhax-Minecraft/Dark-Utilities#36]
So lol tnt might be blown up form normal tnt and well yea i think you know how bad this good be

**Comment by darkhax** [comment]
Explosions created by fake TNT, the one with LOL on it, will not create an explosion that can break blocks. In a situation where the block is exploded by real tnt, only the real tnt block will do block damage. It is not possible for fake tnt to break blocks by exploding.
