### ISSUE TITLE
Crafting Unstable Enderpearls config name is spelled incorrectly "enderpealr"

### ISSUE THREAD

**Issue by toastertim** [Darkhax-Minecraft/Dark-Utilities#37]
![config section in latest version](https://cloud.githubusercontent.com/assets/9875007/22098493/cc2c44b4-dde3-11e6-9305-3ff1a3fa3d71.png)

**Comment by darkhax** [comment]
Lol, thank you for pointing this out. It will be fixed in the next update. Expect said update to override all previous modifications to specifically this config option.
