### ISSUE TITLE
DarkUtils Sneaky Block Client crash

### ISSUE THREAD

**Issue by aaronmallen** [Darkhax-Minecraft/Dark-Utilities#38]
Client crash after placing EnderIO quite clear glass underneath a sneaky false block textured with quite clear glass.  The crash  is happening on a server, but the client is what is crashing not the server.

```
Minecraft: 1.10.2
Dark Utilities: 1.1.6.105
```
[crash-2017-01-21_01.28.21-client.txt](https://github.com/Darkhax-Minecraft/Dark-Utilities/files/720981/crash-2017-01-21_01.28.21-client.txt)

**Comment by darkhax** [comment]
This would be an issue with EnderIO not checking if the block is actually their own block. Please kindly request that they add a check to detect this.

**Comment by laurad2423** [comment]
I'm having the same issue with a chisel block. I don't have it with marble, but I do have it with voidstone.

**Comment by darkhax** [comment]
@laurad2423 Have you updated to the latest version? This issue was fixed.
