### ISSUE TITLE
Filter blocks pass light

### ISSUE THREAD

**Issue by uecasm** [Darkhax-Minecraft/Dark-Utilities#39]
Despite looking like solid blocks, light appears to pass through the filter blocks.  (Currently using the baby and inverse baby filters.)

It would be nice if these blocks blocked light, since it's easier to add light where needed than to block it where not wanted (eg. leaking into a mob farm).

Using version 1.1.6.105 on Minecraft 1.10.2.

(Also, on a peripherally related note, the descriptions in JEI for the filter blocks seem reversed.  The "Mob Filter Type: Baby" (black) says "the baby filter only allows baby mobs to move through it" and the "Inverted Mob Filter Type: Baby" (white) says "the baby filter allows anything but baby mobs to move through it".  Except that the white filter is actually what stops babies and the black filter lets them pass.  Similarly the black player filter lets players pass and the white one stops them.)

**Comment by darkhax** [comment]
Thanks for the report, I will add this to the list for the next update.

**Comment by uecasm** [comment]
Also possibly the textures are flipped too.  When you have a black block and a white block, I would assume that a black block is a "blacklist" and blocks the entity type (is solid for that type), but it's the other way around.  This might just be a matter of taste though.
