### ISSUE TITLE
animal feeder

### ISSUE THREAD

**Issue by zedner** [Darkhax-Minecraft/Dark-Utilities#4]
i noticed that you can feed animals with any type of food, not only with food that those animals actually use, for example i just fed cows and sheeps with carrots...

**Comment by darkhax** [comment]
Yes, this is the intended behavior of the feeder. I did it this way to allow for all animal types to be supported, without other mods adding in support for the mod. I am currently on the fence over whether this is over powered or not, however given the limited inventory size, it balances itself out.

**Comment by zedner** [comment]
ok then, i taught it was bug :)
