### ISSUE TITLE
Vector Plate Ramps

### ISSUE THREAD

**Issue by kingskybomber14** [Darkhax-Minecraft/Dark-Utilities#42]
I love using vector plates to get travel around my base and i think it would be really useful if there was a vector plate ramp or something of the sort which also went up.

This would definitely be an enhancement request, but i dont know how to label so if someone else knows how to label this, please do so.

**Comment by darkhax** [comment]
While this is a good idea, I have some other vector plate plans. Stay tuned to the 1.11.2 version for more info.
