### ISSUE TITLE
Upgrade vector plates

### ISSUE THREAD

**Issue by gigabit101** [Darkhax-Minecraft/Dark-Utilities#43]
Add the ability to craft a sneaky block with a vector plate.
This will make it so only that entity will travel on that plate.
eg: baby mob sneaky block with vector plate (only allow plate to move baby mobs)

**Comment by darkhax** [comment]
Do you mean to craft a filter with the sneaky block?

**Comment by gigabit101** [comment]
yes craft with I mean it will be simple todo but making the block a tile to store that value to and not adding like 20 more variations of blocks might be better
