### ISSUE TITLE
[Mod Compatibility] Sneaky blocks & Tinker's Construct

### ISSUE THREAD

**Issue by chimericdream** [Darkhax-Minecraft/Dark-Utilities#44]
I wanted to use a sneaky block next to a Tinker's smeltery, and I wanted to use seared bricks so it would blend in. But it looks like Tinker's blocks aren't supported yet.

**Comment by darkhax** [comment]
Tinkers smeltery bricks are tile entities. The sneaky blocks intentionally wont work with tile entities to prevent all the misc issues that can cause.

**Comment by chimericdream** [comment]
While I am disappointed to hear that, I understand the reasoning for it. I'll figure out a different way to get the effect I was going for.
