### ISSUE TITLE
[Bug] [1.10.2] sneaky blocks crash when adjacent to EnderIO fused quartz

### ISSUE THREAD

**Issue by UpcraftLP** [Darkhax-Minecraft/Dark-Utilities#45]
when placing EnderIO fused quartz or quite clear glass on top of any sneaky block that has already taken the texture of another block (doesn't matter what), the game crashes when the sneaky block tries to get the blockstate of the enderIO block.

I found this bug on a dedicated server, but was able to reproduce it in a singleplayer world as well.

I attached one the crash logs;
The modpack I was playing is [Hypothermia](https://minecraft.curseforge.com/projects/hypothermia) on the latest version (1.4d)
[crash-2017-02-25_17.35.30-client.txt](https://github.com/Darkhax-Minecraft/Dark-Utilities/files/801335/crash-2017-02-25_17.35.30-client.txt)

**Comment by darkhax** [comment]
This issue was fixed a while ago. Yell at Epiic and Kiba for not updating mods in the pack if this is still an issue.
