### ISSUE TITLE
Sneaky Lever powering incorrectly.

### ISSUE THREAD

**Issue by BromeHelstrom** [Darkhax-Minecraft/Dark-Utilities#47]
Sneaky Lever in it's default state does not provide redstone power to adjacent blocks(as expected), however it does provided power to the redstone next to it.
http://prntscr.com/eg62oz As you can see redstone to the left and bellow the cobble block are on, but the redstone connected directly to the lever is off.

Edit:This is in Skyfactory 3, 1.10.2 3.07 with DUtils Version 1.1.7.112

**Comment by PapiDimmi** [comment]
Duplicate of #31. This is _not_ a bug with Ender IO.
