### ISSUE TITLE
Vector Plates changing orientation when chunks unloaded

### ISSUE THREAD

**Issue by Hjaldar** [Darkhax-Minecraft/Dark-Utilities#50]
Bug **present** with DarkUtilities-1.10.2-1.1.7.116.jar
Bug **not present** with DarkUtilities-1.10.2-1.1.7.112.jar

Using Forge-12.18.3.2254

All placed vector plates (all tiers) reset to facing south when the chunk they are in is either unloaded or outside render distance (not sure which it is). This happens with both newly placed plates and plates placed before upgrading to 1.1.7.116. Curiously, downgrading to 1.1.7.112 fixed the orientation of all the plates I placed before upgrading. This is not just a visual issue; plate behaviour is also affected.

Steps to reproduce:

1. Place plates in varying orientations.
2. Move 20 chunks away.
3. Return to find all plates facing south.

Please let me know if you need further information.

**Comment by jk1895** [comment]
I'm so glad that I'm not the only one with this problem because nobody reported it until now. :)

**Comment by darkhax** [comment]
Thanks to both of you for testing alpha builds and reporting bugs :) I accidently deleted a few lines of code, which is what caused this issue.

**Comment by Hjaldar** [comment]
Thanks for the fix darkhax. Confirmed fixed in 118 public release.
