### ISSUE TITLE
Crash when breaking sneaky block with chisel texture.

### ISSUE THREAD

**Issue by Pieterv24** [Darkhax-Minecraft/Dark-Utilities#55]
Client craches when a sneaky block is broken while it has the texture of a chisel block.
Tested with sneaky block and sneaky false block.
Suspect all sneaky blocks are affected.
Suspect something goes wrong while rendering the breaking texture on the block.

Minecraft 1.10.2
Dark-Utilities 1.1.7.111
Chisel 0.0.8.12

[crash-2017-03-17_16.15.36-client.txt](https://github.com/Darkhax-Minecraft/Dark-Utilities/files/850983/crash-2017-03-17_16.15.36-client.txt)

**Comment by darkhax** [comment]
I *think* this is an issue with Chisel. Likely something they've changed recently, as this was working at one point.

**Comment by tterrag1098** [comment]
Nope, you are feeding our render system `null` as the render layer, which is invalid. While a `null` layer is used for break texture rendering, it is *never* sent to `canRenderInLayer`.

**Comment by tterrag1098** [comment]
Here's the problem line: https://github.com/Darkhax-Minecraft/Dark-Utilities/blob/master/src/main/java/net/darkhax/darkutils/features/sneaky/ModelSneakyBlock.java#L65

Just short circuit the `canRenderInLayer` check with `layer == null`
