### ISSUE TITLE
Block Update Detector breaks when touched by liquid

### ISSUE THREAD

**Issue by MasterEric** [Darkhax-Minecraft/Dark-Utilities#56]
Mod Version: 1.10.2-1.1.7.118

The block update detector breaks when liquid touches it, not unlike a torch.

The issue is here:

https://github.com/Darkhax-Minecraft/Dark-Utilities/blob/master/src/main/java/net/darkhax/darkutils/features/updatedetector/BlockUpdateDetector.java#L23

The circuit material breaks when touched by liquid, please switch to stone or something similar so I can detect when a liquid changes (for example, when Actual Additions oil changes to empowered oil)

**Comment by darkhax** [comment]
This is technically an intended feature. That said, I can see why it would be annoying for players. Will fix this in the next update.
