### ISSUE TITLE
1.11.2 version: issue with baubles integration and bookshelf 

### ISSUE THREAD

**Issue by kragnoth** [Darkhax-Minecraft/Dark-Utilities#58]
I needed to revert bookshelf to the 354 version on minecraft 1.11.2, otherwise I would get the following crash:

https://pastebin.com/7Cn97tw2

Reverting to previous version nullifies crash, but baubles do not go in the bauble slot.  Everything else seems to work great though.

Is there a specific version of baubles you are compiling against for 1.11.2?

**Comment by darkhax** [comment]
Baubles support is broken across all versions in 1.11.2. This will be fixed soon. I am taking the time to do a lot of heavy refactoring to the Bookshelf lib for 1.11.2, which means a lot of me breaking things. Currently I would recommend sticking to the latest dark utilities, and the version of Bookshelf that it was specifically compiled against, which is 353 for the version you're using. 354 should also work fine though.

**Comment by darkhax** [comment]
This has since been resolved, please use the latest builds of Bookshelf, Baubles and Dark Utilities. (Sorry, forgot to update/close the issue when it was fixed)
