### ISSUE TITLE
Sneaky pressure plates do not blend with blocks with connected textures

### ISSUE THREAD

**Issue by ghost** [Darkhax-Minecraft/Dark-Utilities#60]
![2017-04-08_19 05 45](https://cloud.githubusercontent.com/assets/25916106/24830873/836b6694-1c8e-11e7-897b-b19ab1c99dda.png)

**Comment by darkhax** [comment]
This is an issue with all the sneaky blocks in general. It's related to the model for chisel blocks (and other ctm things) checking for a block that is the same type as them. This is why the sneaky blocks will sometimes connect with themselves, or with others, but others will not connect with them. Not sure if it is possible to fix this on my end.

**Comment by DinnerBeef** [comment]
yea that is like everything that does something like that
i do not know anyone that knows how to fix that

**Comment by darkhax** [comment]
I am going to consider this unfixable for now. Sorry :/
