### ISSUE TITLE
Sneaky pressure plates don’t always work immediately

### ISSUE THREAD

**Issue by PapiDimmi** [Darkhax-Minecraft/Dark-Utilities#61]
Sometimes, there’s a slight delay that stops your momentum when walking or sprinting towards a sneaky pressure plate next to a door.

This makes it impossible to smoothly move into and out of buildings like you can with vanilla pressure plates.

**Comment by darkhax** [comment]
After further testing, the plate will always update the next tick that an entity is on them. If there is a lot of server lag it will take longer. This isn't something I can fix on my end.

**Comment by PapiDimmi** [comment]
Well, that took long.

**Comment by PapiDimmi** [comment]
Well, that took a while.

**Comment by jaredlll08** [comment]
Must have been a lot of server lag ;)
