### ISSUE TITLE
The recipe of the sleep charm does not use Ore Dictionary beds

### ISSUE THREAD

**Issue by PapiDimmi** [Darkhax-Minecraft/Dark-Utilities#62]
One cannot use beds from other mods, like Quark, to craft the sleep charm, so if you have Quark installed, you _need_ red wool to craft the sleep charm.

**Comment by darkhax** [comment]
Beds are not included in the standard ore dictionary. So I am guessing that Quark adds this oredict entry themselves. I am down for accepting new oredict standards though. If you report this to anyone else, you should include that Quark is using `bed` for the item and `blockBed` for the block, so we can spread this new standard.

**Comment by PapiDimmi** [comment]
Thanks. 🙂 I really enjoy your mod! Keep doing what you’re doing.

**Comment by darkhax** [comment]
This issue hasn't been fixed, still need to push a dark utilities update for it.

**Comment by PapiDimmi** [comment]
I know. I’m just saying that I appreciate your dedication.

**Comment by darkhax** [comment]
I was referring to you closing the issue. I like to keep them open until they're actually fixed, that way I don't forget about them. Also, are you on 1.10.2 or 1.11.2? I am currently fixing this in 1.11.2, however I will back port it if you're on 1.10.2.

**Comment by PapiDimmi** [comment]
Oh, I see. My bad!

I’m on 1.10.2.

**Comment by PapiDimmi** [comment]
Kind of doesn’t matter in 1.12, though. 😛
