### ISSUE TITLE
Wrenching Deletes Items in Dark-Utilities Chests

### ISSUE THREAD

**Issue by Havvy** [Darkhax-Minecraft/Dark-Utilities#65]
I've tested with the following wrenches, and found that when used on a dark utilities chest, they reset the inventory, deleting everything inside of it:

* Ender IO's
* Forestry's
* IndustrialCraft's
* Redstone Arsenal's
* Refined Storage's

**Comment by darkhax** [comment]
Thanks for reporting this bug. I've since removed chests completely, due to a few really big bugs with them. They will likely see a return some time in 1.12. I have played around with a new system which doesn't have this issue. It's just not ready to implement yet.
