### ISSUE TITLE
Timer doesnt remember settings 90% of the time

### ISSUE THREAD

**Issue by Jemsuper** [Darkhax-Minecraft/Dark-Utilities#66]
Every time i give the timer a new set time it just forgets it when i reopen the timer

**Comment by darkhax** [comment]
Which version is this on?

**Comment by desht** [comment]
I'm seeing this too, in v1.10.2-1.1.7.120 (the version in Age of Engineering 0.4.3).  I can update the time in the GUI, but it doesn't take, either by pressing Enter or clicking the Done button - when I open the GUI again, the timer is still on 100 ticks.

**Comment by darkhax** [comment]
This issue was fixed in 1.11.2, however I have backported this fix, and several others to 1.10.2. You can get the new version [here](https://minecraft.curseforge.com/projects/dark-utilities/files/2422077)
