### ISSUE TITLE
Vector plates not placeable 

### ISSUE THREAD

**Issue by Morticielle** [Darkhax-Minecraft/Dark-Utilities#67]
I'm playing FTB Sky Factory 3 (v3.0.8) on multiplayer and I got the problem that I can't place vector plates on 'Witherproof Glass' (Mystical Agriculture 1.4.3) but I can place it on 'Witherproof Block' from the same mod. I tested it with all three types of vector plates.

Dark Utilities version is 1.10.2-1.1.7.112.

**Comment by darkhax** [comment]
Vector plates have to be placed on a solid block. You can't place them on vanilla glass either.
