### ISSUE TITLE
Crash after Updating to forge 2299

### ISSUE THREAD

**Issue by Medusalem** [Darkhax-Minecraft/Dark-Utilities#69]
Forge 13.20.0.2299
Mod version: 1,11,2-1.2.0.134
Crash Log: https://pastebin.com/mWezqBHE

What Happens:

Game Crashes while loading

It'S a crash in combination with updated Bookshelf.

**Comment by darkhax** [comment]
Bookshelf 2 is a complete rewrite of that mod, and is currently in Alpha. Please stick to the release version (371) until a dark utils update specifically requires V2. Dark Utils will be updating soon.
