### ISSUE TITLE
Incorrect dependency call crashing client

### ISSUE THREAD

**Issue by Gunner76th** [Darkhax-Minecraft/Dark-Utilities#7]
https://github.com/Darkhax-Minecraft/Bookshelf/issues/35#issuecomment-221725961 To simplify this issue post, the orignal post is linked above. 

Client crashes if Bookshelf 251 is used along with Dark Utilities 1.1.0.38 for 1.9.4 This is due to Bookshelf having recently been updated, but Dark Utilities not being updated along with the API. 

Crash report is located here: http://pastebin.com/t3Lp3aNw

Dependency call causing the issue is located here: https://github.com/Darkhax-Minecraft/Dark-Utilities/blob/master/build.gradle#L67

**Comment by Gunner76th** [comment]
Also, no specific version of Bookshelf API is specified for use with the 1.1.0.38 version of Dark Utilities.

**Comment by darkhax** [comment]
Already noticed this, dropped the ball on dependency management. Already fixed in my local branch of the project, just waiting a bit before uploading to CurseForge.

**Comment by darkhax** [comment]
Fixed by 95a2b095acb393f7d75518e2a6cd9792996be8ec
