### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Kodi4444** [Darkhax-Minecraft/Dark-Utilities#70]
The game crashed whilst there was a severe problem during mod loading that has caused the game to fail
The game crashed whilst there was a severe problem during mod loading that has caused the game to fail
Error: net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Dark Utilities (darkutils)

**Comment by darkhax** [comment]
I need the full crash log to know the actual issue.

**Comment by Zeevian** [comment]
[crash-2017-05-23_16.39.30-client.txt](https://github.com/Darkhax-Minecraft/Dark-Utilities/files/1023697/crash-2017-05-23_16.39.30-client.txt)
 this was with only bookshelf and dark util.  

Forge Ver: 1.11.2-forge1.111.2-13.20.0.2304

**Comment by darkhax** [comment]
@zeevian Your crash is the result of using the wrong version of bookshelf. Bookshelf 2 is a complete rewrite, and breaks compatibility with all the mods that dep on it because of that. This is why it is marked as an alpha on CurseForge. Only testers and mod devs should be using it.

**Comment by tiarnia** [comment]
perhaps you should list what version is needed i had same issue with this and i figured the latest bookshelf would go with the latest dark utilities 

after going back to the 1.5 build it works but with out this post i wouldn't have figured that out

**Comment by darkhax** [comment]
@tiarnia The mod page for Bookshelf explicitly tells users not to use any alpha or beta builds unless they know what they know what they're doing (mod devs, and testers), or they were asked to specifically use the alpha/beta. That warning was put in place for exactly this reason.

**Comment by Zeevian** [comment]
@darkhax sorry for the delay, but i was posting in accordance to OP.  It was the only way I initially could cause the crash.  Sorry for not clarifying when I had posted.
