### ISSUE TITLE
Crashes Server

### ISSUE THREAD

**Issue by CamaroKing59** [Darkhax-Minecraft/Dark-Utilities#72]
this shows up about 5 time when i log into a server then the server restarts

unable to determine blocks eligibility for chiseling, net.darkhax.darkutils.features.sneaky.BlockSneaky attempted to load net/minecraft/client/particle/ParticleManager

**Comment by darkhax** [comment]
Hello, I need the full crash log to know the actual issue.

**Comment by CamaroKing59** [comment]
it doesn't generate a full crash log that comes across the console right before crash

**Comment by darkhax** [comment]
A crash log is always generated. Look for `profile folder/logs/fml-client-latest.log`
