### ISSUE TITLE
Server crash 

### ISSUE THREAD

**Issue by frenzye** [Darkhax-Minecraft/Dark-Utilities#74]
https://gist.github.com/frenzye/42e99fc1fd069ffb8c1d91ae54e6ada5 could be related to https://minecraft.curseforge.com/projects/tf2-stuff-mod/issues/7

**Comment by frenzye** [comment]
I don't think it's related to tf2 stuff mod, it's happening without https://gist.github.com/frenzye/5da81360638f8e250bf80250cb511af5

**Comment by darkhax** [comment]
Thank you for reporting. This is a duplicate of https://github.com/Darkhax-Minecraft/Dark-Utilities/issues/68
