### ISSUE TITLE
[1.11.2] Crash on Load

### ISSUE THREAD

**Issue by MokahTGS** [Darkhax-Minecraft/Dark-Utilities#75]
Getting a crash trying to load the 120.134 version.

https://pastebin.com/VunTUQi0

**Comment by darkhax** [comment]
Bookshelf 2 is in early alpha. It is a complete rewrite and breaks compat with this mod. Please use the last release version of Bookshelf, and wait until Bookshelf 2 has a full release before updating.

**Comment by MokahTGS** [comment]
Ah thx
