### ISSUE TITLE
Server Crash Upon Enderman Teleport Event

### ISSUE THREAD

**Issue by TheCahyag** [Darkhax-Minecraft/Dark-Utilities#80]
See edit   V
**Over-Arching Problem:** Current version of Dark-Utilities in FTB Beyond 1.8.1 may be the cause of a server crash when an enderman teleports.

**Environment Details:**
Minecraft Version: Minecraft 1.10.2
Sponge Version: SpongeForge 1.10.2-2281-5.2.0-BETA-2344
Forge: forge-1.10.2-12.18.3.2281-universal
FTB Server: FTBserver-1.10.2-12.18.3.2297
FTB Pack: FTB Beyond 1.8.1
Dark-Utilities: DarkUtilities-1.1.8.finalrc1

**Context and Additional Details:**
As previously stated the server will crash when any loaded enderman teleports. This problem does not occur with DarkUtilities-1.1.8.finalrc2, however, I come here today seeking a solution for the finalrc1 version as that is the pre-defined version in the pack and would be a hassle having anyone who joins having to switch out that mod. 
The crash report is posted here: [https://pastebin.com/BRztN4cU](https://pastebin.com/BRztN4cU)

Let me know if there are any other details I can give or if this is more of a problem for sponge/forge/other.

**Edit:** I just realized this is a dup (my bad), however, is there way to change out the version of the mod without having people who join the server switch it as well?

**Comment by darkhax** [comment]
Yes, it is possible to allow people with other versions to join the server, however that will likely cause some other issues. I will look into it, but I can't promise anything. The ftb beyond team should update the pack soon enough.

**Comment by aequasi** [comment]
Getting this same issue on my server. Not sure if it happens everywhere, but i tried it in the end

**Comment by TheCahyag** [comment]
@aequasi The problem has been fixed in the most recent versions of DarkUtilites, however, if you are running one of the FTB mod packs on a server you will need to wait for FTB to update the mod pack to receive the updated version.

**Comment by darkhax** [comment]
It's not practical for me to allow the new version to let older versions connect at this time. Hopefully FTB will update soon if they haven't already.
