### ISSUE TITLE
Missing GUI?  Crash

### ISSUE THREAD

**Issue by MokahTGS** [Darkhax-Minecraft/Dark-Utilities#82]
What version of Bookshelf is compatible with the 1.11.2-1.2.0.143 version of DU?  Getting a crash with it and the release version of Bookshelf.

Not a great crash too since it doesn't name DU...just missing a UI...Took me forever to figure out what mod was doing it.

https://pastebin.com/KkiUKeFS

**Comment by darkhax** [comment]
The crash you've listed is certainly weird. The crash is caused by forge trying to show you the missing mods gui, and is likely not specific to Dark Utilities. Anyhow, you should use Bookshelf 387.

**Comment by MokahTGS** [comment]
Well the crash only happens with that combo of DU and Bookshelf.

**Comment by savosdarkran** [comment]
That's not true.  I just tried DU and the latest bookshelf and it loads up fine.  I am experiencing a similar issue.  I'm going to pinpoint this to whatever mod requires bookshelf but hasn't updated their codeset to the latest alpha releases.  Give me an hour.
