### ISSUE TITLE
Exception in server tick loop

### ISSUE THREAD

**Issue by Moustik2002** [Darkhax-Minecraft/Dark-Utilities#84]
Hi, whatever version I use i encouter this error, any help would be much appreciated.

It happens only  on server side :

https://pastebin.com/e9H0XD1c

**Comment by darkhax** [comment]
The issue in this crash is that you are using the wrong version of Bookshelf. Bookshelf 2 is experimental and breaks compatibility. If you want to stay on stable, downgrade the the last 1.11.2 release version of bookshelf 1. If you want to use the latest version, upgrade dark utilities to build 143. If either arrangement causes you to crash, please respond with the updated crash log.
