### ISSUE TITLE
[1.11.2 - 1.2.0.143] -- Crash on Server Load

### ISSUE THREAD

**Issue by EPIICTHUNDERCAT** [Darkhax-Minecraft/Dark-Utilities#85]
Yes, I am using releases :)

Dark Utils - 1.2.0.143
Bookshelf - 2.0.388

https://pastebin.com/E282gqBy

**Comment by Mattsingen** [comment]
I can confirm this. Only reverting Dark Utilities to 1.2.0.126 didn't work. I also needed to revert Bookshelf to 1.5.0.371 (I haven't tried any none release builds)

**Comment by The43thAlpha** [comment]
have same problem, error log is same as EPIICTHUNDERCAT
at first glance, seems like the Varied Chests has got issue with the renderer. hope i'm right & that it helped.

Dark utils 1.2.0.143
bookshelf 2.0.0.388
