### ISSUE TITLE
[1.12] Crash on loading new world

### ISSUE THREAD

**Issue by ElectricBlue1** [Darkhax-Minecraft/Dark-Utilities#88]
I have just added Dark Utils for my modapack. Upon testing if anything is broken or would crash I created a world it was created but then my game crashed right after. Log: [crash-2017-06-22_19.34.12-server.txt](https://github.com/Darkhax-Minecraft/Dark-Utilities/files/1096417/crash-2017-06-22_19.34.12-server.txt)

**Comment by darkhax** [comment]
This version requires build 399 of Bookshelf.
