### ISSUE TITLE
1.12 startup crash on worldgen

### ISSUE THREAD

**Issue by Seth0067** [Darkhax-Minecraft/Dark-Utilities#89]
[crash log](https://pastebin.com/FbcJyGje)

used in conjunction with mcjty's "lost cities" mod and biomes o plenty. started a new world with the "tall buildings" mode enabled and the game crashed before the world loaded.

**Comment by darkhax** [comment]
The version of Bookshelf you are using is outdated. Update to [399](https://minecraft.curseforge.com/projects/bookshelf/files/2439199).
