### ISSUE TITLE
Couldn't set damage of loot item 1xitem.darkutils.potion@0

### ISSUE THREAD

**Issue by whatthedrunk** [Darkhax-Minecraft/Dark-Utilities#9]
![cant-log-in](https://cloud.githubusercontent.com/assets/8105116/17035587/092889f8-4f3d-11e6-8ab6-77f1aa0e7b31.png)

A few users are starting to get this message, not sure if it's this mod doing it but it looks like it is.

**Comment by darkhax** [comment]
From the information you have provided, this is not related to my mod. Could you provide logs as well?

**Comment by whatthedrunk** [comment]
Yeah the only reason I am posted it here is because the darkutils part. Here is a pretty large log.
http://pastebin.com/4aEW9nNx Line 67 is where it happens.

**Comment by whatthedrunk** [comment]
Tried to disable the mod but still got the issue, still no clue whats going on but I will close this here. Thanks.
