### ISSUE TITLE
Config file location

### ISSUE THREAD

**Issue by joklbash** [Darkhax-Minecraft/Dark-Utilities#93]
Following should be changed. It's writing to the root of the drive instead of the config folder.

ConfigurationHandler.initConfig(new File("/config/darkutils.cfg"));

**Comment by darkhax** [comment]
Thanks for reporting this!

**Comment by darkhax** [comment]
The download for this fix is [here](https://minecraft.curseforge.com/projects/dark-utilities/files/2445031)
