### ISSUE TITLE
Ender Tether Crashes the server

### ISSUE THREAD

**Issue by Darkere** [Darkhax-Minecraft/Dark-Utilities#94]
Using an ender tether crashes once an enderman teleports in the area.

[Crash report](https://pastebin.com/Tivb9Ji2)

Version 1.12-1.6.156

**Comment by chameleoon** [comment]
I can confirm:
Crash report: [https://pastebin.com/ksfNEFFd](url)

**Comment by darkhax** [comment]
Thank you both for reporting this. Bounding boxes are such a pain to work with, lots of other modders like to do weird things to them. I've added a patch that should fix this, if you could update to [build 159](https://minecraft.curseforge.com/projects/dark-utilities/files/2446604) and test it out that would be great.

**Comment by LukeLonas** [comment]
I tested with the latest alpha build of both Dark Utilities and Bookshelf.  I managed to load into my world that was crashing on joining, but now the tether seems to have no effect on Enderman or Ender teleportation.

**Comment by darkhax** [comment]
I've put out a new build which should fix this. You can find it [here](https://minecraft.curseforge.com/projects/dark-utilities/files/2446856).

**Comment by LukeLonas** [comment]
Thanks, seems to work perfectly now!
