### ISSUE TITLE
sneaky torch crashes the server

### ISSUE THREAD

**Issue by sorc23** [Darkhax-Minecraft/Dark-Utilities#96]
Tried to use a sneaky torch to see how it works and game crashed 

[crash-2017-07-05_18.45.59-client.txt](https://github.com/Darkhax-Minecraft/Dark-Utilities/files/1126350/crash-2017-07-05_18.45.59-client.txt)

**Comment by darkhax** [comment]
Looking at the log, this is specifically an issue on Xaero's Minimap's end. Did you give me the right crash?

**Comment by sorc23** [comment]
I might not have let me look again and see if I gave the wrong one

**Comment by sorc23** [comment]
i will also try it again maybe the launcher for minecraft is putting out the wrong errors

**Comment by sorc23** [comment]
im going to close this seems that launcher is acting up im sorry for wasting your time
