### ISSUE TITLE
Server crash on startup (1.12)

### ISSUE THREAD

**Issue by PrinceApache** [Darkhax-Minecraft/Dark-Utilities#97]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  LoadingPlugin (ResourceLoader-MC1.12-1.5.2.jar)
  ShetiPhian-ASM (shetiphiancore-1.12.0-3.5.0.1.jar)
  AstralCore (astralsorcery-1.5.8.jar)
  AppleCore (AppleCore-mc1.12-2.2.1.jar)
  ForgelinPlugin (Forgelin-1.5.0.jar)
  Inventory Tweaks Coremod (InventoryTweaks-1.63+dev.98.jar)
  Do not report to Forge! Remove FoamFixAPI (or replace with FoamFixAPI-Lawful) and try again. (foamfix-0.7.3-1.12-anarchy.jar)
  LoadingPlugin (Bloodmoon-MC1.12-1.5.1.jar)
  CTMCorePlugin (CTM-MC1.12-0.1.1.2.jar)
  CoreMod (Aroma1997Core-1.12-1.3.0.0.b94.jar)
  LoadingPlugin (Quark-r1.2-99.jar)
  BlurPlugin (Blur-1.0.3-13.jar)
  LoadingPlugin (RandomThings-MC1.12-4.0.2.jar)
Contact their authors BEFORE contacting forge

// Why did you do that?

Time: 2017-07-06 21:11
Description: Exception in server tick loop

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Dark Utilities (darkutils)
Caused by: java.lang.NoClassDefFoundError: net/minecraft/client/renderer/color/IItemColor
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Unknown Source)
	at net.darkhax.bookshelf.util.AnnotationUtils.getAnnotations(AnnotationUtils.java:163)
	at net.darkhax.darkutils.features.FeatureManager.init(FeatureManager.java:23)
	at net.darkhax.darkutils.DarkUtils.onConstruction(DarkUtils.java:81)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:628)
	at sun.reflect.GeneratedMethodAccessor10.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:252)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:230)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:147)
	at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:570)
	at net.minecraftforge.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:97)
	at net.minecraftforge.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:335)
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:122)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:483)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.ClassNotFoundException: net.minecraft.client.renderer.color.IItemColor
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 40 more
Caused by: java.lang.NullPointerException
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
	... 42 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_131, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 771252016 bytes (735 MB) / 1066401792 bytes (1017 MB) up to 3806855168 bytes (3630 MB)
	JVM Flags: 0 total; 
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.40 Powered by Forge 14.21.1.2397 144 mods loaded, 144 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UC	minecraft{1.12} [Minecraft] (minecraft.jar) 
	UC	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UC	FML{8.0.99.99} [Forge Mod Loader] (forge-1.12-14.21.1.2397-universal.jar) 
	UC	forge{14.21.1.2397} [Minecraft Forge] (forge-1.12-14.21.1.2397-universal.jar) 
	UC	aroma1997core{1.3.0.0.b94} [Aroma1997Core] (Aroma1997Core-1.12-1.3.0.0.b94.jar) 
	UC	foamfixcore{7.7.4} [FoamFixCore] (minecraft.jar) 
	UC	securitycraft{v1.8.2.2} [SecurityCraft] ([1.12] SecurityCraft v1.8.2.2.jar) 
	UC	adventurebags{0.6} [Adventure Bags] (ab-1.12-0.6r.jar) 
	UC	actuallyadditions{1.12-r113} [Actually Additions] (ActuallyAdditions-1.12-r113.jar) 
	UC	applecore{2.2.1} [AppleCore] (AppleCore-mc1.12-2.2.1.jar) 
	UC	jei{4.7.1.71} [Just Enough Items] (jei_1.12-4.7.1.71.jar) 
	UC	appleskin{1.0.7} [AppleSkin] (AppleSkin-mc1.12-1.0.7.jar) 
	UC	thedragonlib{1.12-4.0.1} [TheDragonLib] (thedragonlib-1.12-4.0.1.jar) 
	UC	armorplus{1.12-11.3.0.7-alpha} [ArmorPlus] (armorplus-1.12-11.3.0.7-alpha.jar) 
	UC	aroma1997corehelper{1.3.0.0.b94} [Aroma1997Core|Helper] (Aroma1997Core-1.12-1.3.0.0.b94.jar) 
	UC	aroma1997sdimension{1.3.0.0.b37} [Aroma1997's Dimensional World] (Aroma1997s-Dimensional-World-1.12-1.3.0.0.b37.jar) 
	UC	astralsorcery{1.5.8} [Astral Sorcery] (astralsorcery-1.5.8.jar) 
	UC	attaineddrops2{3.3.0} [Attained Drops 2] (Attained Drops-1.12-3.3.0.jar) 
	UC	quark{r1.2-99} [Quark] (Quark-r1.2-99.jar) 
	UC	autoreglib{1.3-13} [AutoRegLib] (AutoRegLib-1.3-13.jar) 
	UC	babyanimals{1.11-2} [Baby Animals Model Swapper] (BabyAnimals-1.11-2.jar) 
	UC	bedbugs{@VERSION@} [Bed Bugs] (BedBugs-1.12-1.0.1.jar) 
	UC	betterbuilderswands{0.11.1} [Better Builder's Wands] (BetterBuildersWands-1.12-0.11.1.245+69d0d70.jar) 
	UC	bibliocraft{2.4.2} [BiblioCraft] (BiblioCraft[v2.4.2][MC1.12.0].jar) 
	UC	biomesoplenty{7.0.0.2288} [Biomes O' Plenty] (BiomesOPlenty-1.12-7.0.0.2288-universal.jar) 
	UC	bloodmoon{1.5.1} [Bloodmoon] (Bloodmoon-MC1.12-1.5.1.jar) 
	UC	bookshelf{2.0.412} [Bookshelf] (Bookshelf-1.12-2.0.0.412.jar) 
	UC	ceramics{1.12-1.3.1} [Ceramics] (Ceramics-1.12-1.3.1.jar) 
	UC	chameleon{1.12-4.1.0} [Chameleon] (Chameleon-1.12-4.1.0.jar) 
	UC	chesttransporter{2.8.3} [Chest Transporter] (ChestTransporter-1.12-2.8.3.jar) 
	UC	claybucket{1.0} [Clay Bucket] (ClayBucket-1.12-1.0.jar) 
	UC	codechickenlib{3.1.0.278} [CodeChicken Lib] (CodeChickenLib-1.12-3.1.0.278-universal.jar) 
	UC	redstoneflux{2.0.0} [Redstone Flux] (RedstoneFlux-1.12-2.0.0.1-universal.jar) 
	UC	cofhcore{4.3.1} [CoFH Core] (CoFHCore-1.12-4.3.1.6-universal.jar) 
	UC	cofhworld{1.0.0} [CoFH World] (CoFHWorld-1.12-1.0.0.5-universal.jar) 
	UC	cosmeticarmorreworked{1.12-v1} [CosmeticArmorReworked] (CosmeticArmorReworked-1.12-v1.jar) 
	UC	craftingtweaks{8.1.1} [Crafting Tweaks] (CraftingTweaks_1.12-8.1.1.jar) 
	UC	cyclicmagic{1.5.9} [Cyclic] (Cyclic-1.12-1.5.9.jar) 
	UC	waila{1.8.19} [Waila] (Hwyla-1.8.19-B33_1.12.jar) 
	UE	darkutils{1.6.159} [Dark Utilities] (DarkUtils-1.12-1.6.159.jar) 
	UC	ic2{2.8.4-ex112} [IndustrialCraft 2] (industrialcraft-2-2.8.4-ex112.jar) 
	UC	forestry{5.4.3.128} [Forestry] (forestry_1.12-5.4.3.128.jar) 
	UC	eleccore{1.8.428} [ElecCore] (ElecCore-1.12-1.8.428.jar) 
	UC	deepresonance{1.4.8} [DeepResonance] (deepresonance-1.12-1.4.8beta1.jar) 
	UC	doggytalents{v1.13.1g} [Doggy Talents] (DoggyTalents-1.12-v1.13.1g-universal.jar) 
	UC	earthworks{1.3.4.3} [Earthworks] (Earthworks-1.12-1.3.4.3.jar) 
	UC	elevatorid{1.3.4} [Elevator Mod] (ElevatorMod-1.12-1.3.4.jar) 
	UC	eggs{1.0} [Eat the Eggs!] (EM3R50N-EatTheEggs-1.12-14.21.1.2387.jar) 
	UC	embers{0.219} [Embers] (embers-0.219.jar) 
	UC	csb_ench_table{1.1.2-beta2} [Lapis Stays in the Enchanting Table] (EnchantingTable-1.12-1.1.2-beta2.jar) 
	UC	endercompass{1.2.6} [Ender Compass] (EnderCompass-1.12-1.2.6.jar) 
	UC	endercrop{1.12-1.3.4} [Ender Crop] (endercrop-1.12-1.3.4.jar) 
	UC	shetiphiancore{3.5.0.1} [ShetiPhian-Core] (shetiphiancore-1.12.0-3.5.0.1.jar) 
	UC	endertanks{1.6.0.1} [EnderTanks] (endertanks-1.12.0-1.6.0.1.jar) 
	UC	enderutilities{0.7.1} [Ender Utilities] (enderutilities-1.12.0-0.7.1.jar) 
	UC	thermalfoundation{2.3.1} [Thermal Foundation] (ThermalFoundation-1.12-2.3.1.5-universal.jar) 
	UC	thermalexpansion{5.3.1} [Thermal Expansion] (ThermalExpansion-1.12-5.3.1.6-universal.jar) 
	UC	exchangers{1.12-2.1.1} [Exchangers] (Exchangers-1.12-2.1.1.jar) 
	UC	zerocore{1.12-0.1.0.9} [Zero CORE] (zerocore-1.12-0.1.0.9.jar) 
	UC	bigreactors{1.12-0.4.5.33} [Extreme Reactors] (ExtremeReactors-1.12-0.4.5.33.jar) 
	UC	fastfood{0.2.20848635} [Fast Food] (FastFood-0.2.20848635.jar) 
	UC	flatbedrockx{1.4.0} [FlatBedrock Xplosion's Edition] (FlatBedrock-1.4.0_1.12.jar) 
	UC	flatcoloredblocks{mc1.12-6.2} [Flat Colored Blocks] (flatcoloredblocks-mc1.12-6.2.jar) 
	UC	floricraft{beta-4.2.0} [Floricraft] (Floricraft-1.12-beta4.2.0.jar) 
	UC	foamfix{@VERSION@} [FoamFix] (foamfix-0.7.3-1.12-anarchy.jar) 
	UC	forgelin{1.4.2} [Shadowfacts' Forgelin] (Forgelin-1.5.0.jar) 
	UC	funkylocomotion{1.0} [Funky Locomotion] (funky-locomotion-1.12-alpha-0.0.1.jar) 
	UC	gravestone{1.8.4} [Gravestone Mod] (gravestone-1.8.4.jar) 
	UC	guideapi{1.12-2.1.3-55} [Guide-API] (Guide-API-1.12-2.1.3-55.jar) 
	UC	immcraft{1.3.3} [Immersive Craft] (immcraft-1.12-1.3.3.jar) 
	UC	infernalmobs{1.7.2} [Infernal Mobs] (InfernalMobs-1.12.jar) 
	UC	inventorytweaks{1.63+dev.98.684f99a} [Inventory Tweaks] (InventoryTweaks-1.63+dev.98.jar) 
	UC	ironchest{1.12-7.0.31.818} [Iron Chest] (ironchest-1.12-7.0.31.818.jar) 
	UC	itorch{1.1.7} [iTorch] (itorch-1.1.7.jar) 
	UC	januslib{0.1-dev} [Janus Compatibility Library] (januslib-0.1.jar) 
	UC	journeymap{1.12-5.4.9} [JourneyMap] (journeymap-1.12-5.4.9.jar) 
	UC	kleeslabs{5.3.2} [KleeSlabs] (KleeSlabs_1.12-5.3.2.jar) 
	UC	shadowmc{3.8.0} [ShadowMC] (ShadowMC-1.12-3.8.0.jar) 
	UC	largeveins{@VERSION@} [Large Veins] (LargeVeins-1.12-1.1.0.jar) 
	UC	mcmultipart{2.2.2} [MCMultiPart] (MCMultiPart-2.2.2.jar) 
	UC	mob_grinding_utils{0.3.1} [mob_grinding_utils] (MobGrindingUtils-0.3.1.jar) 
	UC	morpheus{1.12-3.3.2} [Morpheus] (Morpheus-1.12-3.3.2.jar) 
	UC	terraqueous{1.4.0.1} [Terraqueous] (terraqueous-1.12.0-1.4.0.1.jar) 
	UC	multibeds{1.4.0.1} [Multi-Beds] (multibeds-1.12.0-1.4.0.1.jar) 
	UC	multistorage{1.4.0.1} [Multi-Storage] (multistorage-1.12.0-1.4.0.1.jar) 
	UC	mysticalagriculture{1.6.1} [Mystical Agriculture] (mysticalagriculture[1.12]-1.6.1.jar) 
	UC	mysticalagradditions{1.2.0} [Mystical Agradditions] (mysticalagradditions[1.12]-1.2.0.jar) 
	UC	netherportalfix{1.0} [NetherPortalFix] (NetherPortalFix_1.12-5.3.1.jar) 
	UC	nmsot{1.2.1-mc1.12} [No Mob Spawning on Trees] (NoMobSpawningOnTrees-1.2.1-mc1.12.jar) 
	UC	notenoughwands{1.5.8} [Not Enough Wands] (notenoughwands-1.12-1.5.8.jar) 
	UC	openglider{@VERSION@} [Open Glider] (OpenGlider-1.12-1.0.1.jar) 
	UC	oreexcavation{1.4.100} [OreExcavation] (OreExcavation-1.4.100.jar) 
	UE	desertcraft{1.11a} [Pam's DesertCraft] (Pam's DesertCraft 1.12a.jar) 
	UC	getalltheseeds{1.12a} [Pam's Get all the Seeds!] (Pam's Get all the Seeds! 1.12a.jar) 
	UC	simplerecipes{1.12a} [Pam's Simple Recipes] (Pam's Simple Recipes 1.12a.jar) 
	UC	reborncore{3.2.3.83} [Reborn Core] (RebornCore-1.12-3.2.3.83-universal.jar) 
	UC	quantumstorage{4.3.4} [QuantumStorage] (QuantumStorage-1.12-4.3.4.jar) 
	UC	rainboaks{1.0.4-beta2} [Rainbow Oak Trees] (RainbowOaks-1.12-1.0.4-beta2.jar) 
	UC	randomthings{4.0.2} [Random Things] (RandomThings-MC1.12-4.0.2.jar) 
	UC	rangedpumps{0.5} [Ranged Pumps] (rangedpumps-0.5.jar) 
	UC	redstonearsenal{2.3.1} [Redstone Arsenal] (RedstoneArsenal-1.12-2.3.1.5-universal.jar) 
	UC	refinedrelocation{4.1.4} [Refined Relocation] (RefinedRelocation_1.12-4.1.4.jar) 
	UC	refinedstorage{1.5.7} [Refined Storage] (refinedstorage-1.5.7.jar) 
	UC	reptilemod{3.8.0} [Reptile Mod] (reptilemod-1.12-3.8.0-70.jar) 
	UC	rftools{6.10} [RFTools] (rftools-1.12-6.10beta3.jar) 
	UC	rftoolscontrol{1.6.8} [RFTools Control] (rftoolsctrl-1.12-1.6.8beta1.jar) 
	UC	rftoolsdim{5.02} [RFTools Dimensions] (rftoolsdim-1.12-5.02beta1.jar) 
	UC	roots{0.024} [Roots 2] (roots-2-0.024.jar) 
	UC	silentlib{2.2.5} [Silent Lib] (SilentLib-1.12-2.2.5b-81.jar) 
	UC	silentgems{2.4.0} [Silent's Gems] (SilentsGems-1.12-2.4.0-202.jar) 
	UC	lteleporters{1.11.2-2.1.4} [Simple Teleporters] (simpleteleporters-1.12-2.1.4.jar) 
	UC	simplyconveyors{3.0.6} [Simply Conveyors & More] (SimplyConveyors-4.0.1.jar) 
	UC	simplytea{1.4} [Simply Tea] (simplytea-1.4.jar) 
	UC	soulshardstow{1.12-2.7.3-52} [Soul Shards - The Old Ways] (SoulShards-TOW-1.12-2.7.3-52.jar) 
	UC	spectritemod{1.2.0} [Spectrite Mod] (spectritemod-1.2.0-1.12.jar) 
	UC	spiceoflife{1.3.10} [The Spice of Life] (SpiceOfLife-mc1.12-1.3.10.jar) 
	UC	statues{0.7.1.1} [Statues mod] (statues-0.7.1.1.jar) 
	UC	stevescarts{${version}} [Steve's Carts 2] (StevesCarts-1.12-2.4.4.25.jar) 
	UC	stg{1.12-1.2.0} [SwingThroughGrass] (stg-1.12-1.2.0.jar) 
	UC	storagedrawers{1.12-5.2.0} [Storage Drawers] (StorageDrawers-1.12-5.2.0.jar) 
	UC	storagedrawersextra{@VERSION@} [Storage Drawers Extras] (StorageDrawersExtras-1.12-3.1.0.jar) 
	UC	techreborn{2.6.6.151} [Tech Reborn] (TechReborn-1.12-2.6.6.151-universal.jar) 
	UC	tesla{1.0.61} [TESLA] (Tesla-1.12-1.0.61.jar) 
	UC	thermaldynamics{2.3.1} [Thermal Dynamics] (ThermalDynamics-1.12-2.3.1.6-universal.jar) 
	UC	thut_wearables{3.0.0} [Thut's Wearables] (thut_wearables-3.0.0.d.jar) 
	UC	thutcore{5.0.1} [ThutCore] (thutcore-5.0.1.b.jar) 
	UC	thut_bling{2.0.0} [Thut's Bling] (thut_bling-2.0.0.d.jar) 
	UC	toolbelt{1.6.4} [Tool Belt] (ToolBelt-1.12.0-1.6.4.jar) 
	UC	torchmaster{1.5.0.31} [TorchMaster] (torchmaster_1.12-1.5.0.31.jar) 
	UC	totemic{1.12-0.8.10} [Totemic] (Totemic-1.12-0.8.10.jar) 
	UC	trashslot{8.4.1} [TrashSlot] (TrashSlot_1.12-8.4.1.jar) 
	UC	uniquecrops{0.1.2} [Unique Crops] (uniquecrops-1.12-0.1.2.jar) 
	UC	usefulnullifiers{1.4.1} [Useful Nullifiers] (usefulnullifiers-1.4.1.jar) 
	UC	vefluids{@MAJOR@.@MINOR@.@REVIS@.@BUILD@} [VoltzEngine Fluids module] (VE-FluidHandling-1.12-0.8.0b20170630141359.jar) 
	UC	waddles{0.5.3} [Waddles] (Waddles-1.12-0.5.3.jar) 
	UC	waterpower{@MODVERSION@} [WaterPower] (WaterPower-1.12-0.5.2.jar) 
	UC	waterstrainer{3.1.1} [Water Strainer] (WaterStrainer-1.12-3.1.1.jar) 
	UC	wawla{2.5.239} [What Are We Looking At] (Wawla-1.12-2.5.239.jar) 
	UC	waystones{4.0.5} [Waystones] (Waystones_1.12-4.0.5.jar) 
	UC	woodenbucket{@MAJOR@.@MINOR@.@REVIS@.@BUILD@} [Wooden Bucket] (WoodenBuckets-1.12-0.2.0b20170630140308.jar) 
	UC	xnet{1.3.4.3} [XNet] (xnet-1.12-1.3.4.3.jar) 
	UC	xtones{1.12-1.0.4-7} [Xtones] (Xtones-1.12-1.0.4-7.jar) 
	UC	yeoldetanks{2.1.0} [Ye Olde Tanks] (YeOldeTanks-1.12-2.1.0.jar) 
	UC	zombie_steak{1.12-1.2} [Zombie Steak] (zombie_steak-1.12-1.1.4.jar) 
	Loaded coremods (and transformers): 
LoadingPlugin (ResourceLoader-MC1.12-1.5.2.jar)
  lumien.resourceloader.asm.ClassTransformer
ShetiPhian-ASM (shetiphiancore-1.12.0-3.5.0.1.jar)
  shetiphian.asm.ClassTransformer
AstralCore (astralsorcery-1.5.8.jar)
  
AppleCore (AppleCore-mc1.12-2.2.1.jar)
  squeek.applecore.asm.TransformerModuleHandler
ForgelinPlugin (Forgelin-1.5.0.jar)
  
Inventory Tweaks Coremod (InventoryTweaks-1.63+dev.98.jar)
  invtweaks.forge.asm.ContainerTransformer
Do not report to Forge! Remove FoamFixAPI (or replace with FoamFixAPI-Lawful) and try again. (foamfix-0.7.3-1.12-anarchy.jar)
  pl.asie.foamfix.coremod.FoamFixTransformer
LoadingPlugin (Bloodmoon-MC1.12-1.5.1.jar)
  lumien.bloodmoon.asm.ClassTransformer
CTMCorePlugin (CTM-MC1.12-0.1.1.2.jar)
  team.chisel.ctm.client.asm.CTMTransformer
CoreMod (Aroma1997Core-1.12-1.3.0.0.b94.jar)
  
LoadingPlugin (Quark-r1.2-99.jar)
  vazkii.quark.base.asm.ClassTransformer
BlurPlugin (Blur-1.0.3-13.jar)
  com.tterrag.blur.BlurTransformer
LoadingPlugin (RandomThings-MC1.12-4.0.2.jar)
  lumien.randomthings.asm.ClassTransformer
	Profiler Position: N/A (disabled)
	Is Modded: Definitely; Server brand changed to 'fml,forge'
	Type: Dedicated Server (map_server.txt)

**Comment by darkhax** [comment]
Thank you for reporting this issue. It should be fixed in [this](https://minecraft.curseforge.com/projects/dark-utilities/files/2446856) release. If it says file not found, Curse is processing it still.
