### ISSUE TITLE
Crash During Server Startup

### ISSUE THREAD

**Issue by LukeLonas** [Darkhax-Minecraft/Dark-Utilities#98]
Both mods worked fine on my client test world and fixed the issue I was having with the ender tether, but once I tried to load it up on my server I started getting this crash on startup: https://pastebin.com/aYc6zABs 

- DarkUtils-1.12-1.6.160
- Bookshelf-1.12-2.0.0.412

**Comment by darkhax** [comment]
Thanks for the report, a new build will be automatically uploaded to Curse soon. Mojang keeps doing really weird things with their color code formatting. It will be live [here](https://minecraft.curseforge.com/projects/dark-utilities/files/2446921)
