### ISSUE TITLE
[1.12] Crash After 2/7

### ISSUE THREAD

**Issue by ElectricBlue1** [Darkhax-Minecraft/Dark-Utilities#99]
I was test modpack with updates and DarkUtils had a crash. Crash: [crash-2017-07-06_20.01.35-client.txt](https://github.com/Darkhax-Minecraft/Dark-Utilities/files/1129571/crash-2017-07-06_20.01.35-client.txt)
 
**DarkUtilies: 1.6.1 [1.12]**
**Forge: 14.21.0.2397 [1.12]**

**Comment by darkhax** [comment]
Looks like you found the issue? This version of DarkUtils requires a newer version of Bookshelf. Sorry for not having it marked as a release.

**Comment by ElectricBlue1** [comment]
its fine. I realized there were updates and it fixed the issue :)
